// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: governance.proto

package systemSmartContracts

import (
	bytes "bytes"
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_multiversx_mx_chain_core_go_data "github.com/multiversx/mx-chain-core-go/data"
	io "io"
	math "math"
	math_big "math/big"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VoteValueType int32

const (
	Yes     VoteValueType = 0
	No      VoteValueType = 1
	Veto    VoteValueType = 2
	Abstain VoteValueType = 3
)

var VoteValueType_name = map[int32]string{
	0: "Yes",
	1: "No",
	2: "Veto",
	3: "Abstain",
}

var VoteValueType_value = map[string]int32{
	"Yes":     0,
	"No":      1,
	"Veto":    2,
	"Abstain": 3,
}

func (VoteValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{0}
}

type GeneralProposal struct {
	Nonce          uint64        `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce"`
	CommitHash     []byte        `protobuf:"bytes,2,opt,name=CommitHash,proto3" json:"CommitHash"`
	StartVoteEpoch uint64        `protobuf:"varint,3,opt,name=StartVoteEpoch,proto3" json:"StartVoteEpoch"`
	EndVoteEpoch   uint64        `protobuf:"varint,4,opt,name=EndVoteEpoch,proto3" json:"EndVoteEpoch"`
	Yes            *math_big.Int `protobuf:"bytes,5,opt,name=Yes,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"Yes"`
	No             *math_big.Int `protobuf:"bytes,6,opt,name=No,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"No"`
	Veto           *math_big.Int `protobuf:"bytes,7,opt,name=Veto,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"Veto"`
	Abstain        *math_big.Int `protobuf:"bytes,8,opt,name=Abstain,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"Abstain"`
	QuorumStake    *math_big.Int `protobuf:"bytes,9,opt,name=QuorumStake,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"QuorumStake"`
	Passed         bool          `protobuf:"varint,10,opt,name=Passed,proto3" json:"Passed"`
	Closed         bool          `protobuf:"varint,11,opt,name=Closed,proto3" json:"Closed"`
	IssuerAddress  []byte        `protobuf:"bytes,12,opt,name=IssuerAddress,proto3" json:"IssuerAddress"`
	ProposalCost   *math_big.Int `protobuf:"bytes,13,opt,name=ProposalCost,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"ProposalCost"`
}

func (m *GeneralProposal) Reset()      { *m = GeneralProposal{} }
func (*GeneralProposal) ProtoMessage() {}
func (*GeneralProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{0}
}
func (m *GeneralProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GeneralProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GeneralProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralProposal.Merge(m, src)
}
func (m *GeneralProposal) XXX_Size() int {
	return m.Size()
}
func (m *GeneralProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralProposal.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralProposal proto.InternalMessageInfo

func (m *GeneralProposal) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *GeneralProposal) GetCommitHash() []byte {
	if m != nil {
		return m.CommitHash
	}
	return nil
}

func (m *GeneralProposal) GetStartVoteEpoch() uint64 {
	if m != nil {
		return m.StartVoteEpoch
	}
	return 0
}

func (m *GeneralProposal) GetEndVoteEpoch() uint64 {
	if m != nil {
		return m.EndVoteEpoch
	}
	return 0
}

func (m *GeneralProposal) GetYes() *math_big.Int {
	if m != nil {
		return m.Yes
	}
	return nil
}

func (m *GeneralProposal) GetNo() *math_big.Int {
	if m != nil {
		return m.No
	}
	return nil
}

func (m *GeneralProposal) GetVeto() *math_big.Int {
	if m != nil {
		return m.Veto
	}
	return nil
}

func (m *GeneralProposal) GetAbstain() *math_big.Int {
	if m != nil {
		return m.Abstain
	}
	return nil
}

func (m *GeneralProposal) GetQuorumStake() *math_big.Int {
	if m != nil {
		return m.QuorumStake
	}
	return nil
}

func (m *GeneralProposal) GetPassed() bool {
	if m != nil {
		return m.Passed
	}
	return false
}

func (m *GeneralProposal) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *GeneralProposal) GetIssuerAddress() []byte {
	if m != nil {
		return m.IssuerAddress
	}
	return nil
}

func (m *GeneralProposal) GetProposalCost() *math_big.Int {
	if m != nil {
		return m.ProposalCost
	}
	return nil
}

type GovernanceConfig struct {
	NumNodes         int64         `protobuf:"varint,1,opt,name=NumNodes,proto3" json:"NumNodes"`
	MinQuorum        int32         `protobuf:"varint,2,opt,name=MinQuorum,proto3" json:"MinQuorum"`
	MinPassThreshold int32         `protobuf:"varint,3,opt,name=MinPassThreshold,proto3" json:"MinPassThreshold"`
	MinVetoThreshold int32         `protobuf:"varint,4,opt,name=MinVetoThreshold,proto3" json:"MinVetoThreshold"`
	ProposalFee      *math_big.Int `protobuf:"bytes,5,opt,name=ProposalFee,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"ProposalFee"`
}

func (m *GovernanceConfig) Reset()      { *m = GovernanceConfig{} }
func (*GovernanceConfig) ProtoMessage() {}
func (*GovernanceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{1}
}
func (m *GovernanceConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GovernanceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GovernanceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GovernanceConfig.Merge(m, src)
}
func (m *GovernanceConfig) XXX_Size() int {
	return m.Size()
}
func (m *GovernanceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GovernanceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GovernanceConfig proto.InternalMessageInfo

func (m *GovernanceConfig) GetNumNodes() int64 {
	if m != nil {
		return m.NumNodes
	}
	return 0
}

func (m *GovernanceConfig) GetMinQuorum() int32 {
	if m != nil {
		return m.MinQuorum
	}
	return 0
}

func (m *GovernanceConfig) GetMinPassThreshold() int32 {
	if m != nil {
		return m.MinPassThreshold
	}
	return 0
}

func (m *GovernanceConfig) GetMinVetoThreshold() int32 {
	if m != nil {
		return m.MinVetoThreshold
	}
	return 0
}

func (m *GovernanceConfig) GetProposalFee() *math_big.Int {
	if m != nil {
		return m.ProposalFee
	}
	return nil
}

type GovernanceConfigV2 struct {
	MinQuorum         float32       `protobuf:"fixed32,1,opt,name=MinQuorum,proto3" json:"MinQuorum"`
	MinPassThreshold  float32       `protobuf:"fixed32,2,opt,name=MinPassThreshold,proto3" json:"MinPassThreshold"`
	MinVetoThreshold  float32       `protobuf:"fixed32,3,opt,name=MinVetoThreshold,proto3" json:"MinVetoThreshold"`
	ProposalFee       *math_big.Int `protobuf:"bytes,4,opt,name=ProposalFee,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"ProposalFee"`
	LostProposalFee   *math_big.Int `protobuf:"bytes,5,opt,name=LostProposalFee,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"LostProposalFee"`
	LastProposalNonce uint64        `protobuf:"varint,6,opt,name=LastProposalNonce,proto3" json:"LastProposalNonce"`
}

func (m *GovernanceConfigV2) Reset()      { *m = GovernanceConfigV2{} }
func (*GovernanceConfigV2) ProtoMessage() {}
func (*GovernanceConfigV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{2}
}
func (m *GovernanceConfigV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GovernanceConfigV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GovernanceConfigV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GovernanceConfigV2.Merge(m, src)
}
func (m *GovernanceConfigV2) XXX_Size() int {
	return m.Size()
}
func (m *GovernanceConfigV2) XXX_DiscardUnknown() {
	xxx_messageInfo_GovernanceConfigV2.DiscardUnknown(m)
}

var xxx_messageInfo_GovernanceConfigV2 proto.InternalMessageInfo

func (m *GovernanceConfigV2) GetMinQuorum() float32 {
	if m != nil {
		return m.MinQuorum
	}
	return 0
}

func (m *GovernanceConfigV2) GetMinPassThreshold() float32 {
	if m != nil {
		return m.MinPassThreshold
	}
	return 0
}

func (m *GovernanceConfigV2) GetMinVetoThreshold() float32 {
	if m != nil {
		return m.MinVetoThreshold
	}
	return 0
}

func (m *GovernanceConfigV2) GetProposalFee() *math_big.Int {
	if m != nil {
		return m.ProposalFee
	}
	return nil
}

func (m *GovernanceConfigV2) GetLostProposalFee() *math_big.Int {
	if m != nil {
		return m.LostProposalFee
	}
	return nil
}

func (m *GovernanceConfigV2) GetLastProposalNonce() uint64 {
	if m != nil {
		return m.LastProposalNonce
	}
	return 0
}

type OngoingVotedList struct {
	Direct    []uint64 `protobuf:"varint,1,rep,packed,name=Direct,proto3" json:"Direct"`
	Delegated []uint64 `protobuf:"varint,2,rep,packed,name=Delegated,proto3" json:"Delegated"`
}

func (m *OngoingVotedList) Reset()      { *m = OngoingVotedList{} }
func (*OngoingVotedList) ProtoMessage() {}
func (*OngoingVotedList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{3}
}
func (m *OngoingVotedList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OngoingVotedList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *OngoingVotedList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OngoingVotedList.Merge(m, src)
}
func (m *OngoingVotedList) XXX_Size() int {
	return m.Size()
}
func (m *OngoingVotedList) XXX_DiscardUnknown() {
	xxx_messageInfo_OngoingVotedList.DiscardUnknown(m)
}

var xxx_messageInfo_OngoingVotedList proto.InternalMessageInfo

func (m *OngoingVotedList) GetDirect() []uint64 {
	if m != nil {
		return m.Direct
	}
	return nil
}

func (m *OngoingVotedList) GetDelegated() []uint64 {
	if m != nil {
		return m.Delegated
	}
	return nil
}

type OngoingVotedListV2 struct {
	Direct               []uint64                `protobuf:"varint,1,rep,packed,name=Direct,proto3" json:"Direct"`
	Delegated            []uint64                `protobuf:"varint,2,rep,packed,name=Delegated,proto3" json:"Delegated"`
	DelegatedWithAddress []*DelegatedWithAddress `protobuf:"bytes,3,rep,name=DelegatedWithAddress,proto3" json:"DelegatedWithAddress"`
}

func (m *OngoingVotedListV2) Reset()      { *m = OngoingVotedListV2{} }
func (*OngoingVotedListV2) ProtoMessage() {}
func (*OngoingVotedListV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{4}
}
func (m *OngoingVotedListV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OngoingVotedListV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *OngoingVotedListV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OngoingVotedListV2.Merge(m, src)
}
func (m *OngoingVotedListV2) XXX_Size() int {
	return m.Size()
}
func (m *OngoingVotedListV2) XXX_DiscardUnknown() {
	xxx_messageInfo_OngoingVotedListV2.DiscardUnknown(m)
}

var xxx_messageInfo_OngoingVotedListV2 proto.InternalMessageInfo

func (m *OngoingVotedListV2) GetDirect() []uint64 {
	if m != nil {
		return m.Direct
	}
	return nil
}

func (m *OngoingVotedListV2) GetDelegated() []uint64 {
	if m != nil {
		return m.Delegated
	}
	return nil
}

func (m *OngoingVotedListV2) GetDelegatedWithAddress() []*DelegatedWithAddress {
	if m != nil {
		return m.DelegatedWithAddress
	}
	return nil
}

type DelegatedWithAddress struct {
	Nonce            uint64 `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	DelegatedAddress []byte `protobuf:"bytes,2,opt,name=DelegatedAddress,proto3" json:"DelegatedAddress"`
}

func (m *DelegatedWithAddress) Reset()      { *m = DelegatedWithAddress{} }
func (*DelegatedWithAddress) ProtoMessage() {}
func (*DelegatedWithAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{5}
}
func (m *DelegatedWithAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegatedWithAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DelegatedWithAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatedWithAddress.Merge(m, src)
}
func (m *DelegatedWithAddress) XXX_Size() int {
	return m.Size()
}
func (m *DelegatedWithAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatedWithAddress.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatedWithAddress proto.InternalMessageInfo

func (m *DelegatedWithAddress) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DelegatedWithAddress) GetDelegatedAddress() []byte {
	if m != nil {
		return m.DelegatedAddress
	}
	return nil
}

type DelegatedSCVoteInfo struct {
	TotalPower *math_big.Int `protobuf:"bytes,1,opt,name=TotalPower,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"TotalPower"`
	UsedPower  *math_big.Int `protobuf:"bytes,2,opt,name=UsedPower,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"UsedPower"`
	TotalStake *math_big.Int `protobuf:"bytes,3,opt,name=TotalStake,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"TotalStake"`
	UsedStake  *math_big.Int `protobuf:"bytes,4,opt,name=UsedStake,proto3,casttypewith=math/big.Int;github.com/multiversx/mx-chain-core-go/data.BigIntCaster" json:"UsedStake"`
}

func (m *DelegatedSCVoteInfo) Reset()      { *m = DelegatedSCVoteInfo{} }
func (*DelegatedSCVoteInfo) ProtoMessage() {}
func (*DelegatedSCVoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e18a03da5266c714, []int{6}
}
func (m *DelegatedSCVoteInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegatedSCVoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DelegatedSCVoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatedSCVoteInfo.Merge(m, src)
}
func (m *DelegatedSCVoteInfo) XXX_Size() int {
	return m.Size()
}
func (m *DelegatedSCVoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatedSCVoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatedSCVoteInfo proto.InternalMessageInfo

func (m *DelegatedSCVoteInfo) GetTotalPower() *math_big.Int {
	if m != nil {
		return m.TotalPower
	}
	return nil
}

func (m *DelegatedSCVoteInfo) GetUsedPower() *math_big.Int {
	if m != nil {
		return m.UsedPower
	}
	return nil
}

func (m *DelegatedSCVoteInfo) GetTotalStake() *math_big.Int {
	if m != nil {
		return m.TotalStake
	}
	return nil
}

func (m *DelegatedSCVoteInfo) GetUsedStake() *math_big.Int {
	if m != nil {
		return m.UsedStake
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.VoteValueType", VoteValueType_name, VoteValueType_value)
	proto.RegisterType((*GeneralProposal)(nil), "proto.GeneralProposal")
	proto.RegisterType((*GovernanceConfig)(nil), "proto.GovernanceConfig")
	proto.RegisterType((*GovernanceConfigV2)(nil), "proto.GovernanceConfigV2")
	proto.RegisterType((*OngoingVotedList)(nil), "proto.OngoingVotedList")
	proto.RegisterType((*OngoingVotedListV2)(nil), "proto.OngoingVotedListV2")
	proto.RegisterType((*DelegatedWithAddress)(nil), "proto.DelegatedWithAddress")
	proto.RegisterType((*DelegatedSCVoteInfo)(nil), "proto.DelegatedSCVoteInfo")
}

func init() { proto.RegisterFile("governance.proto", fileDescriptor_e18a03da5266c714) }

var fileDescriptor_e18a03da5266c714 = []byte{
	// 972 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x8f, 0xe3, 0x24, 0x6d, 0xa7, 0xe9, 0xae, 0x77, 0x28, 0x92, 0x05, 0x92, 0x27, 0xca, 0x29,
	0x02, 0x35, 0x91, 0x0a, 0xd2, 0x4a, 0x70, 0xd9, 0x75, 0xb6, 0x2c, 0x95, 0xba, 0xd9, 0xae, 0x5b,
	0xb2, 0x2c, 0x42, 0x42, 0x93, 0x78, 0xea, 0x58, 0xc4, 0x33, 0x95, 0x67, 0xb2, 0x7f, 0x90, 0x90,
	0x38, 0x71, 0x85, 0x8f, 0x81, 0xf8, 0x24, 0x1c, 0x7b, 0xec, 0xc9, 0xd0, 0xf4, 0x02, 0x16, 0x87,
	0x95, 0xf8, 0x02, 0x68, 0xc6, 0x89, 0xff, 0x24, 0xbd, 0x54, 0x58, 0x9c, 0x66, 0xde, 0xef, 0xcd,
	0xfc, 0x7e, 0x7e, 0xcf, 0x6f, 0x66, 0x1e, 0x30, 0x3c, 0xf6, 0x92, 0x84, 0x14, 0xd3, 0x31, 0xe9,
	0x9e, 0x87, 0x4c, 0x30, 0x58, 0x57, 0xc3, 0x7b, 0x7b, 0x9e, 0x2f, 0x26, 0xb3, 0x51, 0x77, 0xcc,
	0x82, 0x9e, 0xc7, 0x3c, 0xd6, 0x53, 0xf0, 0x68, 0x76, 0xa6, 0x2c, 0x65, 0xa8, 0x59, 0xb2, 0xab,
	0xfd, 0xf7, 0x06, 0xb8, 0xfb, 0x98, 0x50, 0x12, 0xe2, 0xe9, 0x71, 0xc8, 0xce, 0x19, 0xc7, 0x53,
	0x88, 0x40, 0x7d, 0xc0, 0xe8, 0x98, 0x98, 0x5a, 0x4b, 0xeb, 0xd4, 0xec, 0xad, 0x38, 0x42, 0x09,
	0xe0, 0x24, 0x03, 0xec, 0x02, 0xd0, 0x67, 0x41, 0xe0, 0x8b, 0xcf, 0x31, 0x9f, 0x98, 0xd5, 0x96,
	0xd6, 0x69, 0xda, 0x77, 0xe2, 0x08, 0xe5, 0x50, 0x27, 0x37, 0x87, 0x9f, 0x80, 0x3b, 0x27, 0x02,
	0x87, 0x62, 0xc8, 0x04, 0x39, 0x38, 0x67, 0xe3, 0x89, 0xa9, 0x2b, 0x66, 0x18, 0x47, 0x68, 0xc5,
	0xe3, 0xac, 0xd8, 0xf0, 0x63, 0xd0, 0x3c, 0xa0, 0x6e, 0xb6, 0xb3, 0xa6, 0x76, 0x1a, 0x71, 0x84,
	0x0a, 0xb8, 0x53, 0xb0, 0xe0, 0x08, 0xe8, 0x2f, 0x08, 0x37, 0xeb, 0xea, 0xd3, 0x8e, 0xe3, 0x08,
	0x49, 0xf3, 0xd7, 0xdf, 0xd1, 0x41, 0x80, 0xc5, 0xa4, 0x37, 0xf2, 0xbd, 0xee, 0x21, 0x15, 0x9f,
	0xe6, 0x52, 0x15, 0xcc, 0xa6, 0xc2, 0x7f, 0x49, 0x42, 0xfe, 0xba, 0x17, 0xbc, 0xde, 0x1b, 0x4f,
	0xb0, 0x4f, 0xf7, 0xc6, 0x2c, 0x24, 0x7b, 0x1e, 0xeb, 0xb9, 0x58, 0xe0, 0xae, 0xed, 0x7b, 0x87,
	0x54, 0xf4, 0x31, 0x17, 0x24, 0x74, 0x24, 0x1b, 0xfc, 0x06, 0x54, 0x07, 0xcc, 0x6c, 0x28, 0x89,
	0xa7, 0x71, 0x84, 0xaa, 0x03, 0x56, 0x9e, 0x42, 0x75, 0xc0, 0x20, 0x01, 0xb5, 0x21, 0x11, 0xcc,
	0xdc, 0x50, 0x12, 0xcf, 0xe2, 0x08, 0x29, 0xbb, 0x3c, 0x11, 0x45, 0x07, 0x29, 0xd8, 0x78, 0x38,
	0xe2, 0x02, 0xfb, 0xd4, 0xdc, 0x54, 0x4a, 0xa7, 0x71, 0x84, 0x96, 0x50, 0x79, 0x62, 0x4b, 0x46,
	0xf8, 0x1d, 0xd8, 0x7e, 0x36, 0x63, 0xe1, 0x2c, 0x38, 0x11, 0xf8, 0x5b, 0x62, 0x6e, 0x29, 0xcd,
	0x2f, 0xe3, 0x08, 0xe5, 0xe1, 0xf2, 0x74, 0xf3, 0xac, 0xb0, 0x0d, 0x1a, 0xc7, 0x98, 0x73, 0xe2,
	0x9a, 0xa0, 0xa5, 0x75, 0x36, 0x6d, 0x10, 0x47, 0x68, 0x81, 0x38, 0x8b, 0x51, 0xae, 0xe9, 0x4f,
	0x99, 0x5c, 0xb3, 0x9d, 0xad, 0x49, 0x10, 0x67, 0x31, 0xc2, 0xfb, 0x60, 0xe7, 0x90, 0xf3, 0x19,
	0x09, 0x1f, 0xba, 0x6e, 0x48, 0x38, 0x37, 0x9b, 0x2a, 0x8a, 0x7b, 0x71, 0x84, 0x8a, 0x0e, 0xa7,
	0x68, 0xc2, 0xef, 0x41, 0x73, 0x79, 0xce, 0xfa, 0x8c, 0x0b, 0x73, 0x47, 0xed, 0x7b, 0x21, 0xcb,
	0x39, 0x8f, 0x97, 0x17, 0x7e, 0x81, 0xb6, 0xfd, 0x57, 0x15, 0x18, 0x8f, 0xd3, 0x9b, 0xa3, 0xcf,
	0xe8, 0x99, 0xef, 0xc1, 0x0e, 0xd8, 0x1c, 0xcc, 0x82, 0x01, 0x73, 0x09, 0x57, 0x47, 0x5e, 0xb7,
	0x9b, 0x71, 0x84, 0x52, 0xcc, 0x49, 0x67, 0xf0, 0x43, 0xb0, 0xf5, 0xc4, 0xa7, 0x49, 0x42, 0xd5,
	0xb9, 0xaf, 0xdb, 0x3b, 0x71, 0x84, 0x32, 0xd0, 0xc9, 0xa6, 0xf0, 0x01, 0x30, 0x9e, 0xf8, 0x54,
	0x26, 0xf5, 0x74, 0x12, 0x12, 0x3e, 0x61, 0x53, 0x57, 0x9d, 0xfb, 0xba, 0xbd, 0x1b, 0x47, 0x68,
	0xcd, 0xe7, 0xac, 0x21, 0x0b, 0x06, 0x59, 0xa4, 0x19, 0x43, 0xad, 0xc0, 0x50, 0xf0, 0x39, 0x6b,
	0x88, 0xac, 0xb5, 0x65, 0xfc, 0x9f, 0x11, 0xb2, 0xb8, 0x0f, 0x54, 0xad, 0xe5, 0xe0, 0x12, 0x6b,
	0x2d, 0xc7, 0xda, 0xfe, 0xa9, 0x06, 0xe0, 0x6a, 0xae, 0x87, 0xfb, 0xc5, 0x1c, 0xca, 0x74, 0x57,
	0x6f, 0x99, 0xc3, 0xaa, 0xda, 0xf3, 0x5f, 0x72, 0xa8, 0x17, 0x18, 0x6e, 0x99, 0xc3, 0xda, 0xff,
	0x98, 0x43, 0xf8, 0xa3, 0x06, 0xee, 0x1e, 0x31, 0x2e, 0xd6, 0x7f, 0xe2, 0xd7, 0x71, 0x84, 0x56,
	0x5d, 0xe5, 0x7d, 0xc4, 0x2a, 0x33, 0xec, 0x83, 0x7b, 0x47, 0x38, 0x83, 0x92, 0xf7, 0xb1, 0xa1,
	0xde, 0xa2, 0x77, 0xe3, 0x08, 0xad, 0x3b, 0x9d, 0x75, 0xa8, 0x3d, 0x06, 0xc6, 0x53, 0xea, 0x31,
	0x9f, 0x7a, 0xf2, 0xa5, 0x72, 0x8f, 0x7c, 0x2e, 0xe4, 0x6d, 0xf3, 0xc8, 0x0f, 0xc9, 0x58, 0x98,
	0x5a, 0x4b, 0xef, 0xd4, 0x92, 0xdb, 0x26, 0x41, 0x9c, 0xc5, 0x28, 0x4b, 0xe6, 0x11, 0x99, 0x12,
	0x0f, 0x0b, 0x22, 0x7f, 0xbf, 0x5c, 0xa6, 0x4a, 0x26, 0x05, 0x9d, 0x6c, 0xda, 0xbe, 0xd0, 0x00,
	0x5c, 0x55, 0x19, 0xee, 0x97, 0xae, 0x03, 0x7d, 0xb0, 0x9b, 0x1a, 0xcf, 0x7d, 0x31, 0x59, 0xde,
	0x84, 0x7a, 0x4b, 0xef, 0x6c, 0xef, 0xbf, 0x9f, 0xf4, 0x17, 0xdd, 0x9b, 0x96, 0xd8, 0x66, 0x1c,
	0xa1, 0x1b, 0x37, 0x3b, 0x37, 0xa2, 0x6d, 0x7a, 0xb3, 0x14, 0xdc, 0x2d, 0x34, 0x2a, 0xcb, 0xee,
	0xe4, 0x01, 0x30, 0xd2, 0xd5, 0xcb, 0x8f, 0x4a, 0x7a, 0x14, 0x55, 0xf1, 0xab, 0x3e, 0x67, 0x0d,
	0x69, 0xff, 0xa3, 0x83, 0x77, 0x52, 0xf0, 0xa4, 0x2f, 0xd3, 0x78, 0x48, 0xcf, 0x18, 0x7c, 0x05,
	0xc0, 0x29, 0x13, 0x78, 0x7a, 0xcc, 0x5e, 0x91, 0x50, 0x89, 0x36, 0xed, 0xe7, 0xb2, 0xef, 0xc9,
	0xd0, 0xf2, 0x4a, 0x30, 0x47, 0x0a, 0x05, 0xd8, 0xfa, 0x82, 0x13, 0x37, 0xd1, 0x4d, 0x62, 0x19,
	0xca, 0x1f, 0x93, 0x82, 0xe5, 0xc9, 0x66, 0x9c, 0x69, 0xb8, 0xc9, 0x3b, 0xad, 0xaf, 0x84, 0x5b,
	0xf2, 0x33, 0x9d, 0x23, 0x5d, 0x86, 0x9b, 0xe8, 0xd6, 0x8a, 0xe1, 0x96, 0x2c, 0x9b, 0x71, 0x7e,
	0x70, 0x1f, 0xec, 0xc8, 0x3f, 0x3d, 0xc4, 0xd3, 0x19, 0x39, 0x7d, 0x73, 0x4e, 0xe0, 0x86, 0x6a,
	0x22, 0x8d, 0x0a, 0x6c, 0xc8, 0x4e, 0xcf, 0xd0, 0xe0, 0x66, 0xd2, 0x90, 0x19, 0x55, 0xb8, 0x9d,
	0xf6, 0x4c, 0x86, 0x6e, 0x0f, 0x2e, 0xae, 0xac, 0xca, 0xe5, 0x95, 0x55, 0x79, 0x7b, 0x65, 0x69,
	0x3f, 0xcc, 0x2d, 0xed, 0x97, 0xb9, 0xa5, 0xfd, 0x36, 0xb7, 0xb4, 0x8b, 0xb9, 0xa5, 0x5d, 0xce,
	0x2d, 0xed, 0x8f, 0xb9, 0xa5, 0xfd, 0x39, 0xb7, 0x2a, 0x6f, 0xe7, 0x96, 0xf6, 0xf3, 0xb5, 0x55,
	0xb9, 0xb8, 0xb6, 0x2a, 0x97, 0xd7, 0x56, 0xe5, 0xab, 0x5d, 0xfe, 0x86, 0x0b, 0x12, 0x9c, 0x04,
	0x38, 0x14, 0x7d, 0x46, 0x45, 0x88, 0xc7, 0x82, 0x8f, 0x1a, 0xea, 0xe8, 0x7c, 0xf4, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x11, 0xfb, 0x54, 0xe4, 0x0b, 0x00, 0x00,
}

func (x VoteValueType) String() string {
	s, ok := VoteValueType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *GeneralProposal) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GeneralProposal)
	if !ok {
		that2, ok := that.(GeneralProposal)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if !bytes.Equal(this.CommitHash, that1.CommitHash) {
		return false
	}
	if this.StartVoteEpoch != that1.StartVoteEpoch {
		return false
	}
	if this.EndVoteEpoch != that1.EndVoteEpoch {
		return false
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.Yes, that1.Yes) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.No, that1.No) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.Veto, that1.Veto) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.Abstain, that1.Abstain) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.QuorumStake, that1.QuorumStake) {
			return false
		}
	}
	if this.Passed != that1.Passed {
		return false
	}
	if this.Closed != that1.Closed {
		return false
	}
	if !bytes.Equal(this.IssuerAddress, that1.IssuerAddress) {
		return false
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.ProposalCost, that1.ProposalCost) {
			return false
		}
	}
	return true
}
func (this *GovernanceConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GovernanceConfig)
	if !ok {
		that2, ok := that.(GovernanceConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NumNodes != that1.NumNodes {
		return false
	}
	if this.MinQuorum != that1.MinQuorum {
		return false
	}
	if this.MinPassThreshold != that1.MinPassThreshold {
		return false
	}
	if this.MinVetoThreshold != that1.MinVetoThreshold {
		return false
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.ProposalFee, that1.ProposalFee) {
			return false
		}
	}
	return true
}
func (this *GovernanceConfigV2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GovernanceConfigV2)
	if !ok {
		that2, ok := that.(GovernanceConfigV2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinQuorum != that1.MinQuorum {
		return false
	}
	if this.MinPassThreshold != that1.MinPassThreshold {
		return false
	}
	if this.MinVetoThreshold != that1.MinVetoThreshold {
		return false
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.ProposalFee, that1.ProposalFee) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.LostProposalFee, that1.LostProposalFee) {
			return false
		}
	}
	if this.LastProposalNonce != that1.LastProposalNonce {
		return false
	}
	return true
}
func (this *OngoingVotedList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OngoingVotedList)
	if !ok {
		that2, ok := that.(OngoingVotedList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Direct) != len(that1.Direct) {
		return false
	}
	for i := range this.Direct {
		if this.Direct[i] != that1.Direct[i] {
			return false
		}
	}
	if len(this.Delegated) != len(that1.Delegated) {
		return false
	}
	for i := range this.Delegated {
		if this.Delegated[i] != that1.Delegated[i] {
			return false
		}
	}
	return true
}
func (this *OngoingVotedListV2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OngoingVotedListV2)
	if !ok {
		that2, ok := that.(OngoingVotedListV2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Direct) != len(that1.Direct) {
		return false
	}
	for i := range this.Direct {
		if this.Direct[i] != that1.Direct[i] {
			return false
		}
	}
	if len(this.Delegated) != len(that1.Delegated) {
		return false
	}
	for i := range this.Delegated {
		if this.Delegated[i] != that1.Delegated[i] {
			return false
		}
	}
	if len(this.DelegatedWithAddress) != len(that1.DelegatedWithAddress) {
		return false
	}
	for i := range this.DelegatedWithAddress {
		if !this.DelegatedWithAddress[i].Equal(that1.DelegatedWithAddress[i]) {
			return false
		}
	}
	return true
}
func (this *DelegatedWithAddress) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DelegatedWithAddress)
	if !ok {
		that2, ok := that.(DelegatedWithAddress)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if !bytes.Equal(this.DelegatedAddress, that1.DelegatedAddress) {
		return false
	}
	return true
}
func (this *DelegatedSCVoteInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DelegatedSCVoteInfo)
	if !ok {
		that2, ok := that.(DelegatedSCVoteInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.TotalPower, that1.TotalPower) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.UsedPower, that1.UsedPower) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.TotalStake, that1.TotalStake) {
			return false
		}
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		if !__caster.Equal(this.UsedStake, that1.UsedStake) {
			return false
		}
	}
	return true
}
func (this *GeneralProposal) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 17)
	s = append(s, "&systemSmartContracts.GeneralProposal{")
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "CommitHash: "+fmt.Sprintf("%#v", this.CommitHash)+",\n")
	s = append(s, "StartVoteEpoch: "+fmt.Sprintf("%#v", this.StartVoteEpoch)+",\n")
	s = append(s, "EndVoteEpoch: "+fmt.Sprintf("%#v", this.EndVoteEpoch)+",\n")
	s = append(s, "Yes: "+fmt.Sprintf("%#v", this.Yes)+",\n")
	s = append(s, "No: "+fmt.Sprintf("%#v", this.No)+",\n")
	s = append(s, "Veto: "+fmt.Sprintf("%#v", this.Veto)+",\n")
	s = append(s, "Abstain: "+fmt.Sprintf("%#v", this.Abstain)+",\n")
	s = append(s, "QuorumStake: "+fmt.Sprintf("%#v", this.QuorumStake)+",\n")
	s = append(s, "Passed: "+fmt.Sprintf("%#v", this.Passed)+",\n")
	s = append(s, "Closed: "+fmt.Sprintf("%#v", this.Closed)+",\n")
	s = append(s, "IssuerAddress: "+fmt.Sprintf("%#v", this.IssuerAddress)+",\n")
	s = append(s, "ProposalCost: "+fmt.Sprintf("%#v", this.ProposalCost)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GovernanceConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&systemSmartContracts.GovernanceConfig{")
	s = append(s, "NumNodes: "+fmt.Sprintf("%#v", this.NumNodes)+",\n")
	s = append(s, "MinQuorum: "+fmt.Sprintf("%#v", this.MinQuorum)+",\n")
	s = append(s, "MinPassThreshold: "+fmt.Sprintf("%#v", this.MinPassThreshold)+",\n")
	s = append(s, "MinVetoThreshold: "+fmt.Sprintf("%#v", this.MinVetoThreshold)+",\n")
	s = append(s, "ProposalFee: "+fmt.Sprintf("%#v", this.ProposalFee)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GovernanceConfigV2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&systemSmartContracts.GovernanceConfigV2{")
	s = append(s, "MinQuorum: "+fmt.Sprintf("%#v", this.MinQuorum)+",\n")
	s = append(s, "MinPassThreshold: "+fmt.Sprintf("%#v", this.MinPassThreshold)+",\n")
	s = append(s, "MinVetoThreshold: "+fmt.Sprintf("%#v", this.MinVetoThreshold)+",\n")
	s = append(s, "ProposalFee: "+fmt.Sprintf("%#v", this.ProposalFee)+",\n")
	s = append(s, "LostProposalFee: "+fmt.Sprintf("%#v", this.LostProposalFee)+",\n")
	s = append(s, "LastProposalNonce: "+fmt.Sprintf("%#v", this.LastProposalNonce)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OngoingVotedList) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&systemSmartContracts.OngoingVotedList{")
	s = append(s, "Direct: "+fmt.Sprintf("%#v", this.Direct)+",\n")
	s = append(s, "Delegated: "+fmt.Sprintf("%#v", this.Delegated)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OngoingVotedListV2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&systemSmartContracts.OngoingVotedListV2{")
	s = append(s, "Direct: "+fmt.Sprintf("%#v", this.Direct)+",\n")
	s = append(s, "Delegated: "+fmt.Sprintf("%#v", this.Delegated)+",\n")
	if this.DelegatedWithAddress != nil {
		s = append(s, "DelegatedWithAddress: "+fmt.Sprintf("%#v", this.DelegatedWithAddress)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DelegatedWithAddress) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&systemSmartContracts.DelegatedWithAddress{")
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "DelegatedAddress: "+fmt.Sprintf("%#v", this.DelegatedAddress)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DelegatedSCVoteInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&systemSmartContracts.DelegatedSCVoteInfo{")
	s = append(s, "TotalPower: "+fmt.Sprintf("%#v", this.TotalPower)+",\n")
	s = append(s, "UsedPower: "+fmt.Sprintf("%#v", this.UsedPower)+",\n")
	s = append(s, "TotalStake: "+fmt.Sprintf("%#v", this.TotalStake)+",\n")
	s = append(s, "UsedStake: "+fmt.Sprintf("%#v", this.UsedStake)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringGovernance(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *GeneralProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GeneralProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GeneralProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.ProposalCost)
		i -= size
		if _, err := __caster.MarshalTo(m.ProposalCost, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if len(m.IssuerAddress) > 0 {
		i -= len(m.IssuerAddress)
		copy(dAtA[i:], m.IssuerAddress)
		i = encodeVarintGovernance(dAtA, i, uint64(len(m.IssuerAddress)))
		i--
		dAtA[i] = 0x62
	}
	if m.Closed {
		i--
		if m.Closed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.Passed {
		i--
		if m.Passed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.QuorumStake)
		i -= size
		if _, err := __caster.MarshalTo(m.QuorumStake, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.Abstain)
		i -= size
		if _, err := __caster.MarshalTo(m.Abstain, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.Veto)
		i -= size
		if _, err := __caster.MarshalTo(m.Veto, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.No)
		i -= size
		if _, err := __caster.MarshalTo(m.No, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.Yes)
		i -= size
		if _, err := __caster.MarshalTo(m.Yes, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.EndVoteEpoch != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.EndVoteEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.StartVoteEpoch != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.StartVoteEpoch))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CommitHash) > 0 {
		i -= len(m.CommitHash)
		copy(dAtA[i:], m.CommitHash)
		i = encodeVarintGovernance(dAtA, i, uint64(len(m.CommitHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GovernanceConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GovernanceConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GovernanceConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.ProposalFee)
		i -= size
		if _, err := __caster.MarshalTo(m.ProposalFee, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.MinVetoThreshold != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.MinVetoThreshold))
		i--
		dAtA[i] = 0x20
	}
	if m.MinPassThreshold != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.MinPassThreshold))
		i--
		dAtA[i] = 0x18
	}
	if m.MinQuorum != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.MinQuorum))
		i--
		dAtA[i] = 0x10
	}
	if m.NumNodes != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.NumNodes))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GovernanceConfigV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GovernanceConfigV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GovernanceConfigV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastProposalNonce != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.LastProposalNonce))
		i--
		dAtA[i] = 0x30
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.LostProposalFee)
		i -= size
		if _, err := __caster.MarshalTo(m.LostProposalFee, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.ProposalFee)
		i -= size
		if _, err := __caster.MarshalTo(m.ProposalFee, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.MinVetoThreshold != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.MinVetoThreshold))))
		i--
		dAtA[i] = 0x1d
	}
	if m.MinPassThreshold != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.MinPassThreshold))))
		i--
		dAtA[i] = 0x15
	}
	if m.MinQuorum != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.MinQuorum))))
		i--
		dAtA[i] = 0xd
	}
	return len(dAtA) - i, nil
}

func (m *OngoingVotedList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OngoingVotedList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OngoingVotedList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Delegated) > 0 {
		dAtA2 := make([]byte, len(m.Delegated)*10)
		var j1 int
		for _, num := range m.Delegated {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintGovernance(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Direct) > 0 {
		dAtA4 := make([]byte, len(m.Direct)*10)
		var j3 int
		for _, num := range m.Direct {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintGovernance(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OngoingVotedListV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OngoingVotedListV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OngoingVotedListV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegatedWithAddress) > 0 {
		for iNdEx := len(m.DelegatedWithAddress) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegatedWithAddress[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGovernance(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Delegated) > 0 {
		dAtA6 := make([]byte, len(m.Delegated)*10)
		var j5 int
		for _, num := range m.Delegated {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintGovernance(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Direct) > 0 {
		dAtA8 := make([]byte, len(m.Direct)*10)
		var j7 int
		for _, num := range m.Direct {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintGovernance(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DelegatedWithAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegatedWithAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegatedWithAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DelegatedAddress) > 0 {
		i -= len(m.DelegatedAddress)
		copy(dAtA[i:], m.DelegatedAddress)
		i = encodeVarintGovernance(dAtA, i, uint64(len(m.DelegatedAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintGovernance(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DelegatedSCVoteInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegatedSCVoteInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegatedSCVoteInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.UsedStake)
		i -= size
		if _, err := __caster.MarshalTo(m.UsedStake, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.TotalStake)
		i -= size
		if _, err := __caster.MarshalTo(m.TotalStake, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.UsedPower)
		i -= size
		if _, err := __caster.MarshalTo(m.UsedPower, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		size := __caster.Size(m.TotalPower)
		i -= size
		if _, err := __caster.MarshalTo(m.TotalPower, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGovernance(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGovernance(dAtA []byte, offset int, v uint64) int {
	offset -= sovGovernance(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GeneralProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovGovernance(uint64(m.Nonce))
	}
	l = len(m.CommitHash)
	if l > 0 {
		n += 1 + l + sovGovernance(uint64(l))
	}
	if m.StartVoteEpoch != 0 {
		n += 1 + sovGovernance(uint64(m.StartVoteEpoch))
	}
	if m.EndVoteEpoch != 0 {
		n += 1 + sovGovernance(uint64(m.EndVoteEpoch))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.Yes)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.No)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.Veto)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.Abstain)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.QuorumStake)
		n += 1 + l + sovGovernance(uint64(l))
	}
	if m.Passed {
		n += 2
	}
	if m.Closed {
		n += 2
	}
	l = len(m.IssuerAddress)
	if l > 0 {
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.ProposalCost)
		n += 1 + l + sovGovernance(uint64(l))
	}
	return n
}

func (m *GovernanceConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumNodes != 0 {
		n += 1 + sovGovernance(uint64(m.NumNodes))
	}
	if m.MinQuorum != 0 {
		n += 1 + sovGovernance(uint64(m.MinQuorum))
	}
	if m.MinPassThreshold != 0 {
		n += 1 + sovGovernance(uint64(m.MinPassThreshold))
	}
	if m.MinVetoThreshold != 0 {
		n += 1 + sovGovernance(uint64(m.MinVetoThreshold))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.ProposalFee)
		n += 1 + l + sovGovernance(uint64(l))
	}
	return n
}

func (m *GovernanceConfigV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinQuorum != 0 {
		n += 5
	}
	if m.MinPassThreshold != 0 {
		n += 5
	}
	if m.MinVetoThreshold != 0 {
		n += 5
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.ProposalFee)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.LostProposalFee)
		n += 1 + l + sovGovernance(uint64(l))
	}
	if m.LastProposalNonce != 0 {
		n += 1 + sovGovernance(uint64(m.LastProposalNonce))
	}
	return n
}

func (m *OngoingVotedList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Direct) > 0 {
		l = 0
		for _, e := range m.Direct {
			l += sovGovernance(uint64(e))
		}
		n += 1 + sovGovernance(uint64(l)) + l
	}
	if len(m.Delegated) > 0 {
		l = 0
		for _, e := range m.Delegated {
			l += sovGovernance(uint64(e))
		}
		n += 1 + sovGovernance(uint64(l)) + l
	}
	return n
}

func (m *OngoingVotedListV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Direct) > 0 {
		l = 0
		for _, e := range m.Direct {
			l += sovGovernance(uint64(e))
		}
		n += 1 + sovGovernance(uint64(l)) + l
	}
	if len(m.Delegated) > 0 {
		l = 0
		for _, e := range m.Delegated {
			l += sovGovernance(uint64(e))
		}
		n += 1 + sovGovernance(uint64(l)) + l
	}
	if len(m.DelegatedWithAddress) > 0 {
		for _, e := range m.DelegatedWithAddress {
			l = e.Size()
			n += 1 + l + sovGovernance(uint64(l))
		}
	}
	return n
}

func (m *DelegatedWithAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovGovernance(uint64(m.Nonce))
	}
	l = len(m.DelegatedAddress)
	if l > 0 {
		n += 1 + l + sovGovernance(uint64(l))
	}
	return n
}

func (m *DelegatedSCVoteInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.TotalPower)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.UsedPower)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.TotalStake)
		n += 1 + l + sovGovernance(uint64(l))
	}
	{
		__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
		l = __caster.Size(m.UsedStake)
		n += 1 + l + sovGovernance(uint64(l))
	}
	return n
}

func sovGovernance(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGovernance(x uint64) (n int) {
	return sovGovernance(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *GeneralProposal) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GeneralProposal{`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`CommitHash:` + fmt.Sprintf("%v", this.CommitHash) + `,`,
		`StartVoteEpoch:` + fmt.Sprintf("%v", this.StartVoteEpoch) + `,`,
		`EndVoteEpoch:` + fmt.Sprintf("%v", this.EndVoteEpoch) + `,`,
		`Yes:` + fmt.Sprintf("%v", this.Yes) + `,`,
		`No:` + fmt.Sprintf("%v", this.No) + `,`,
		`Veto:` + fmt.Sprintf("%v", this.Veto) + `,`,
		`Abstain:` + fmt.Sprintf("%v", this.Abstain) + `,`,
		`QuorumStake:` + fmt.Sprintf("%v", this.QuorumStake) + `,`,
		`Passed:` + fmt.Sprintf("%v", this.Passed) + `,`,
		`Closed:` + fmt.Sprintf("%v", this.Closed) + `,`,
		`IssuerAddress:` + fmt.Sprintf("%v", this.IssuerAddress) + `,`,
		`ProposalCost:` + fmt.Sprintf("%v", this.ProposalCost) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GovernanceConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GovernanceConfig{`,
		`NumNodes:` + fmt.Sprintf("%v", this.NumNodes) + `,`,
		`MinQuorum:` + fmt.Sprintf("%v", this.MinQuorum) + `,`,
		`MinPassThreshold:` + fmt.Sprintf("%v", this.MinPassThreshold) + `,`,
		`MinVetoThreshold:` + fmt.Sprintf("%v", this.MinVetoThreshold) + `,`,
		`ProposalFee:` + fmt.Sprintf("%v", this.ProposalFee) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GovernanceConfigV2) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GovernanceConfigV2{`,
		`MinQuorum:` + fmt.Sprintf("%v", this.MinQuorum) + `,`,
		`MinPassThreshold:` + fmt.Sprintf("%v", this.MinPassThreshold) + `,`,
		`MinVetoThreshold:` + fmt.Sprintf("%v", this.MinVetoThreshold) + `,`,
		`ProposalFee:` + fmt.Sprintf("%v", this.ProposalFee) + `,`,
		`LostProposalFee:` + fmt.Sprintf("%v", this.LostProposalFee) + `,`,
		`LastProposalNonce:` + fmt.Sprintf("%v", this.LastProposalNonce) + `,`,
		`}`,
	}, "")
	return s
}
func (this *OngoingVotedList) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OngoingVotedList{`,
		`Direct:` + fmt.Sprintf("%v", this.Direct) + `,`,
		`Delegated:` + fmt.Sprintf("%v", this.Delegated) + `,`,
		`}`,
	}, "")
	return s
}
func (this *OngoingVotedListV2) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForDelegatedWithAddress := "[]*DelegatedWithAddress{"
	for _, f := range this.DelegatedWithAddress {
		repeatedStringForDelegatedWithAddress += strings.Replace(f.String(), "DelegatedWithAddress", "DelegatedWithAddress", 1) + ","
	}
	repeatedStringForDelegatedWithAddress += "}"
	s := strings.Join([]string{`&OngoingVotedListV2{`,
		`Direct:` + fmt.Sprintf("%v", this.Direct) + `,`,
		`Delegated:` + fmt.Sprintf("%v", this.Delegated) + `,`,
		`DelegatedWithAddress:` + repeatedStringForDelegatedWithAddress + `,`,
		`}`,
	}, "")
	return s
}
func (this *DelegatedWithAddress) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DelegatedWithAddress{`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`DelegatedAddress:` + fmt.Sprintf("%v", this.DelegatedAddress) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DelegatedSCVoteInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DelegatedSCVoteInfo{`,
		`TotalPower:` + fmt.Sprintf("%v", this.TotalPower) + `,`,
		`UsedPower:` + fmt.Sprintf("%v", this.UsedPower) + `,`,
		`TotalStake:` + fmt.Sprintf("%v", this.TotalStake) + `,`,
		`UsedStake:` + fmt.Sprintf("%v", this.UsedStake) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGovernance(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *GeneralProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GeneralProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GeneralProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitHash = append(m.CommitHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitHash == nil {
				m.CommitHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartVoteEpoch", wireType)
			}
			m.StartVoteEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartVoteEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndVoteEpoch", wireType)
			}
			m.EndVoteEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndVoteEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.Yes = tmp
				}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field No", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.No = tmp
				}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Veto", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.Veto = tmp
				}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Abstain", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.Abstain = tmp
				}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumStake", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.QuorumStake = tmp
				}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Passed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Passed = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Closed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Closed = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssuerAddress = append(m.IssuerAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.IssuerAddress == nil {
				m.IssuerAddress = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalCost", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.ProposalCost = tmp
				}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GovernanceConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GovernanceConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GovernanceConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumNodes", wireType)
			}
			m.NumNodes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumNodes |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinQuorum", wireType)
			}
			m.MinQuorum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinQuorum |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPassThreshold", wireType)
			}
			m.MinPassThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinPassThreshold |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVetoThreshold", wireType)
			}
			m.MinVetoThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinVetoThreshold |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.ProposalFee = tmp
				}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GovernanceConfigV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GovernanceConfigV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GovernanceConfigV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinQuorum", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.MinQuorum = float32(math.Float32frombits(v))
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPassThreshold", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.MinPassThreshold = float32(math.Float32frombits(v))
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinVetoThreshold", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.MinVetoThreshold = float32(math.Float32frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.ProposalFee = tmp
				}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LostProposalFee", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.LostProposalFee = tmp
				}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastProposalNonce", wireType)
			}
			m.LastProposalNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastProposalNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGovernance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OngoingVotedList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OngoingVotedList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OngoingVotedList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Direct = append(m.Direct, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGovernance
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGovernance
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Direct) == 0 {
					m.Direct = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGovernance
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Direct = append(m.Direct, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Direct", wireType)
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Delegated = append(m.Delegated, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGovernance
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGovernance
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Delegated) == 0 {
					m.Delegated = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGovernance
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Delegated = append(m.Delegated, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegated", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGovernance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OngoingVotedListV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OngoingVotedListV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OngoingVotedListV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Direct = append(m.Direct, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGovernance
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGovernance
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Direct) == 0 {
					m.Direct = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGovernance
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Direct = append(m.Direct, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Direct", wireType)
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Delegated = append(m.Delegated, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGovernance
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGovernance
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGovernance
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Delegated) == 0 {
					m.Delegated = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGovernance
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Delegated = append(m.Delegated, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegated", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatedWithAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatedWithAddress = append(m.DelegatedWithAddress, &DelegatedWithAddress{})
			if err := m.DelegatedWithAddress[len(m.DelegatedWithAddress)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegatedWithAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegatedWithAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegatedWithAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatedAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatedAddress = append(m.DelegatedAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.DelegatedAddress == nil {
				m.DelegatedAddress = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegatedSCVoteInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegatedSCVoteInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegatedSCVoteInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPower", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.TotalPower = tmp
				}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedPower", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.UsedPower = tmp
				}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalStake", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.TotalStake = tmp
				}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedStake", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGovernance
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGovernance
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_multiversx_mx_chain_core_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.UsedStake = tmp
				}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGovernance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGovernance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGovernance(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGovernance
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGovernance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGovernance
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGovernance
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGovernance
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGovernance        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGovernance          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGovernance = fmt.Errorf("proto: unexpected end of group")
)
