// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: peerAccountData.proto

package state

import (
	bytes "bytes"
	encoding_binary "encoding/binary"
	fmt "fmt"
	github_com_ElrondNetwork_elrond_go_data "github.com/ElrondNetwork/elrond-go/data"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_big "math/big"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SignRate is used to keep the number of success and failed signings
type SignRate struct {
	NumSuccess uint32 `protobuf:"varint,1,opt,name=NumSuccess,proto3" json:"NumSuccess,omitempty"`
	NumFailure uint32 `protobuf:"varint,2,opt,name=NumFailure,proto3" json:"NumFailure,omitempty"`
}

func (m *SignRate) Reset()      { *m = SignRate{} }
func (*SignRate) ProtoMessage() {}
func (*SignRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_26bd0314afcce126, []int{0}
}
func (m *SignRate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SignRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRate.Merge(m, src)
}
func (m *SignRate) XXX_Size() int {
	return m.Size()
}
func (m *SignRate) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRate.DiscardUnknown(m)
}

var xxx_messageInfo_SignRate proto.InternalMessageInfo

func (m *SignRate) GetNumSuccess() uint32 {
	if m != nil {
		return m.NumSuccess
	}
	return 0
}

func (m *SignRate) GetNumFailure() uint32 {
	if m != nil {
		return m.NumFailure
	}
	return 0
}

// ValidatorApiResponse represents the data which is fetched from each validator for returning it in API call
type ValidatorApiResponse struct {
	TempRating                         float32 `protobuf:"fixed32,1,opt,name=TempRating,proto3" json:"tempRating"`
	NumLeaderSuccess                   uint32  `protobuf:"varint,2,opt,name=NumLeaderSuccess,proto3" json:"numLeaderSuccess"`
	NumLeaderFailure                   uint32  `protobuf:"varint,3,opt,name=NumLeaderFailure,proto3" json:"numLeaderFailure"`
	NumValidatorSuccess                uint32  `protobuf:"varint,4,opt,name=NumValidatorSuccess,proto3" json:"numValidatorSuccess"`
	NumValidatorFailure                uint32  `protobuf:"varint,5,opt,name=NumValidatorFailure,proto3" json:"numValidatorFailure"`
	NumValidatorIgnoredSignatures      uint32  `protobuf:"varint,6,opt,name=NumValidatorIgnoredSignatures,proto3" json:"numValidatorIgnoredSignatures"`
	Rating                             float32 `protobuf:"fixed32,7,opt,name=Rating,proto3" json:"rating"`
	RatingModifier                     float32 `protobuf:"fixed32,8,opt,name=RatingModifier,proto3" json:"ratingModifier"`
	TotalNumLeaderSuccess              uint32  `protobuf:"varint,9,opt,name=TotalNumLeaderSuccess,proto3" json:"totalNumLeaderSuccess"`
	TotalNumLeaderFailure              uint32  `protobuf:"varint,10,opt,name=TotalNumLeaderFailure,proto3" json:"totalNumLeaderFailure"`
	TotalNumValidatorSuccess           uint32  `protobuf:"varint,11,opt,name=TotalNumValidatorSuccess,proto3" json:"totalNumValidatorSuccess"`
	TotalNumValidatorFailure           uint32  `protobuf:"varint,12,opt,name=TotalNumValidatorFailure,proto3" json:"totalNumValidatorFailure"`
	TotalNumValidatorIgnoredSignatures uint32  `protobuf:"varint,13,opt,name=TotalNumValidatorIgnoredSignatures,proto3" json:"totalNumValidatorIgnoredSignatures"`
	ShardId                            uint32  `protobuf:"varint,14,opt,name=ShardId,proto3" json:"shardId"`
	ValidatorStatus                    string  `protobuf:"bytes,15,opt,name=ValidatorStatus,proto3" json:"validatorStatus,omitempty"`
}

func (m *ValidatorApiResponse) Reset()      { *m = ValidatorApiResponse{} }
func (*ValidatorApiResponse) ProtoMessage() {}
func (*ValidatorApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26bd0314afcce126, []int{1}
}
func (m *ValidatorApiResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ValidatorApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorApiResponse.Merge(m, src)
}
func (m *ValidatorApiResponse) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorApiResponse proto.InternalMessageInfo

func (m *ValidatorApiResponse) GetTempRating() float32 {
	if m != nil {
		return m.TempRating
	}
	return 0
}

func (m *ValidatorApiResponse) GetNumLeaderSuccess() uint32 {
	if m != nil {
		return m.NumLeaderSuccess
	}
	return 0
}

func (m *ValidatorApiResponse) GetNumLeaderFailure() uint32 {
	if m != nil {
		return m.NumLeaderFailure
	}
	return 0
}

func (m *ValidatorApiResponse) GetNumValidatorSuccess() uint32 {
	if m != nil {
		return m.NumValidatorSuccess
	}
	return 0
}

func (m *ValidatorApiResponse) GetNumValidatorFailure() uint32 {
	if m != nil {
		return m.NumValidatorFailure
	}
	return 0
}

func (m *ValidatorApiResponse) GetNumValidatorIgnoredSignatures() uint32 {
	if m != nil {
		return m.NumValidatorIgnoredSignatures
	}
	return 0
}

func (m *ValidatorApiResponse) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *ValidatorApiResponse) GetRatingModifier() float32 {
	if m != nil {
		return m.RatingModifier
	}
	return 0
}

func (m *ValidatorApiResponse) GetTotalNumLeaderSuccess() uint32 {
	if m != nil {
		return m.TotalNumLeaderSuccess
	}
	return 0
}

func (m *ValidatorApiResponse) GetTotalNumLeaderFailure() uint32 {
	if m != nil {
		return m.TotalNumLeaderFailure
	}
	return 0
}

func (m *ValidatorApiResponse) GetTotalNumValidatorSuccess() uint32 {
	if m != nil {
		return m.TotalNumValidatorSuccess
	}
	return 0
}

func (m *ValidatorApiResponse) GetTotalNumValidatorFailure() uint32 {
	if m != nil {
		return m.TotalNumValidatorFailure
	}
	return 0
}

func (m *ValidatorApiResponse) GetTotalNumValidatorIgnoredSignatures() uint32 {
	if m != nil {
		return m.TotalNumValidatorIgnoredSignatures
	}
	return 0
}

func (m *ValidatorApiResponse) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *ValidatorApiResponse) GetValidatorStatus() string {
	if m != nil {
		return m.ValidatorStatus
	}
	return ""
}

// PeerAccountData represents the data that defines the PeerAccount
type PeerAccountData struct {
	BLSPublicKey                        []byte        `protobuf:"bytes,1,opt,name=BLSPublicKey,proto3" json:"blsPublicKey"`
	RewardAddress                       []byte        `protobuf:"bytes,2,opt,name=RewardAddress,proto3" json:"rewardAddress,omitempty"`
	ShardId                             uint32        `protobuf:"varint,3,opt,name=ShardId,proto3" json:"shardId"`
	ValidatorSuccessRate                SignRate      `protobuf:"bytes,4,opt,name=ValidatorSuccessRate,proto3" json:"validatorSuccessRate"`
	LeaderSuccessRate                   SignRate      `protobuf:"bytes,5,opt,name=LeaderSuccessRate,proto3" json:"leaderSuccessRate"`
	ValidatorIgnoredSignaturesRate      uint32        `protobuf:"varint,6,opt,name=ValidatorIgnoredSignaturesRate,proto3" json:"validatorIgnoredSignaturesRate"`
	Rating                              uint32        `protobuf:"varint,7,opt,name=Rating,proto3" json:"rating"`
	TempRating                          uint32        `protobuf:"varint,8,opt,name=TempRating,proto3" json:"tempRating"`
	AccumulatedFees                     *math_big.Int `protobuf:"bytes,9,opt,name=AccumulatedFees,proto3,casttypewith=math/big.Int;github.com/ElrondNetwork/elrond-go/data.BigIntCaster" json:"accumulatedFees,omitempty"`
	NumSelectedInSuccessBlocks          uint32        `protobuf:"varint,10,opt,name=NumSelectedInSuccessBlocks,proto3" json:"numSelectedInSuccessBlocks"`
	IndexInList                         uint32        `protobuf:"varint,11,opt,name=IndexInList,proto3" json:"indexInList"`
	List                                string        `protobuf:"bytes,12,opt,name=List,proto3" json:"list,omitempty"`
	ConsecutiveProposerMisses           uint32        `protobuf:"varint,13,opt,name=ConsecutiveProposerMisses,proto3" json:"consecutiveProposerMisses"`
	TotalValidatorSuccessRate           SignRate      `protobuf:"bytes,14,opt,name=TotalValidatorSuccessRate,proto3" json:"totalValidatorSuccessRate"`
	TotalLeaderSuccessRate              SignRate      `protobuf:"bytes,15,opt,name=TotalLeaderSuccessRate,proto3" json:"totalLeaderSuccessRate"`
	TotalValidatorIgnoredSignaturesRate uint32        `protobuf:"varint,16,opt,name=TotalValidatorIgnoredSignaturesRate,proto3" json:"totalValidatorIgnoredSignaturesRate"`
	Nonce                               uint64        `protobuf:"varint,17,opt,name=Nonce,proto3" json:"nonce"`
	UnStakedEpoch                       uint32        `protobuf:"varint,18,opt,name=UnStakedEpoch,proto3" json:"unStakedEpoch"`
}

func (m *PeerAccountData) Reset()      { *m = PeerAccountData{} }
func (*PeerAccountData) ProtoMessage() {}
func (*PeerAccountData) Descriptor() ([]byte, []int) {
	return fileDescriptor_26bd0314afcce126, []int{2}
}
func (m *PeerAccountData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PeerAccountData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PeerAccountData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAccountData.Merge(m, src)
}
func (m *PeerAccountData) XXX_Size() int {
	return m.Size()
}
func (m *PeerAccountData) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAccountData.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAccountData proto.InternalMessageInfo

func (m *PeerAccountData) GetBLSPublicKey() []byte {
	if m != nil {
		return m.BLSPublicKey
	}
	return nil
}

func (m *PeerAccountData) GetRewardAddress() []byte {
	if m != nil {
		return m.RewardAddress
	}
	return nil
}

func (m *PeerAccountData) GetShardId() uint32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *PeerAccountData) GetValidatorSuccessRate() SignRate {
	if m != nil {
		return m.ValidatorSuccessRate
	}
	return SignRate{}
}

func (m *PeerAccountData) GetLeaderSuccessRate() SignRate {
	if m != nil {
		return m.LeaderSuccessRate
	}
	return SignRate{}
}

func (m *PeerAccountData) GetValidatorIgnoredSignaturesRate() uint32 {
	if m != nil {
		return m.ValidatorIgnoredSignaturesRate
	}
	return 0
}

func (m *PeerAccountData) GetRating() uint32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *PeerAccountData) GetTempRating() uint32 {
	if m != nil {
		return m.TempRating
	}
	return 0
}

func (m *PeerAccountData) GetAccumulatedFees() *math_big.Int {
	if m != nil {
		return m.AccumulatedFees
	}
	return nil
}

func (m *PeerAccountData) GetNumSelectedInSuccessBlocks() uint32 {
	if m != nil {
		return m.NumSelectedInSuccessBlocks
	}
	return 0
}

func (m *PeerAccountData) GetIndexInList() uint32 {
	if m != nil {
		return m.IndexInList
	}
	return 0
}

func (m *PeerAccountData) GetList() string {
	if m != nil {
		return m.List
	}
	return ""
}

func (m *PeerAccountData) GetConsecutiveProposerMisses() uint32 {
	if m != nil {
		return m.ConsecutiveProposerMisses
	}
	return 0
}

func (m *PeerAccountData) GetTotalValidatorSuccessRate() SignRate {
	if m != nil {
		return m.TotalValidatorSuccessRate
	}
	return SignRate{}
}

func (m *PeerAccountData) GetTotalLeaderSuccessRate() SignRate {
	if m != nil {
		return m.TotalLeaderSuccessRate
	}
	return SignRate{}
}

func (m *PeerAccountData) GetTotalValidatorIgnoredSignaturesRate() uint32 {
	if m != nil {
		return m.TotalValidatorIgnoredSignaturesRate
	}
	return 0
}

func (m *PeerAccountData) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *PeerAccountData) GetUnStakedEpoch() uint32 {
	if m != nil {
		return m.UnStakedEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*SignRate)(nil), "proto.SignRate")
	proto.RegisterType((*ValidatorApiResponse)(nil), "proto.ValidatorApiResponse")
	proto.RegisterType((*PeerAccountData)(nil), "proto.PeerAccountData")
}

func init() { proto.RegisterFile("peerAccountData.proto", fileDescriptor_26bd0314afcce126) }

var fileDescriptor_26bd0314afcce126 = []byte{
	// 1011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4b, 0x73, 0xdb, 0x44,
	0x1c, 0xb7, 0xda, 0x3a, 0x8f, 0xb5, 0x1d, 0x27, 0xdb, 0xa4, 0x95, 0x43, 0xa3, 0x4d, 0xdd, 0xa1,
	0xe4, 0x40, 0x93, 0xe1, 0x31, 0xc3, 0x0c, 0x1c, 0xc0, 0x2a, 0x2d, 0x63, 0x48, 0x43, 0x66, 0x53,
	0x98, 0x0e, 0xcc, 0x30, 0xb3, 0x96, 0xb6, 0x8a, 0x88, 0xac, 0xf5, 0x48, 0x2b, 0x97, 0xdc, 0xb8,
	0x70, 0xe3, 0xc0, 0xc7, 0x60, 0xf8, 0x24, 0x3d, 0xe6, 0x98, 0xd3, 0x42, 0x9c, 0x03, 0xcc, 0x9e,
	0xfa, 0x11, 0x18, 0xaf, 0x25, 0x47, 0xb2, 0x24, 0xa7, 0x27, 0x5b, 0xff, 0xdf, 0x63, 0xff, 0xfb,
	0xfa, 0x2d, 0xd8, 0x18, 0x50, 0x1a, 0x74, 0x2c, 0x8b, 0x45, 0x3e, 0xff, 0x92, 0x70, 0xb2, 0x3b,
	0x08, 0x18, 0x67, 0xb0, 0xaa, 0x7e, 0x36, 0x1f, 0x39, 0x2e, 0x3f, 0x8e, 0x7a, 0xbb, 0x16, 0xeb,
	0xef, 0x39, 0xcc, 0x61, 0x7b, 0xaa, 0xdc, 0x8b, 0x5e, 0xaa, 0x2f, 0xf5, 0xa1, 0xfe, 0x4d, 0x54,
	0xed, 0xaf, 0xc1, 0xd2, 0x91, 0xeb, 0xf8, 0x98, 0x70, 0x0a, 0x0d, 0x00, 0x0e, 0xa2, 0xfe, 0x51,
	0x64, 0x59, 0x34, 0x0c, 0x75, 0x6d, 0x5b, 0xdb, 0x69, 0xe0, 0x54, 0x25, 0xc6, 0x9f, 0x12, 0xd7,
	0x8b, 0x02, 0xaa, 0xdf, 0x98, 0xe2, 0x71, 0xa5, 0xfd, 0xef, 0x12, 0x58, 0xff, 0x9e, 0x78, 0xae,
	0x4d, 0x38, 0x0b, 0x3a, 0x03, 0x17, 0xd3, 0x70, 0xc0, 0xfc, 0x90, 0xc2, 0x5d, 0x00, 0x9e, 0xd3,
	0xfe, 0x00, 0x13, 0xee, 0xfa, 0x8e, 0x32, 0xbe, 0x61, 0xae, 0x48, 0x81, 0x00, 0x9f, 0x56, 0x71,
	0x8a, 0x01, 0xbf, 0x00, 0xab, 0x07, 0x51, 0x7f, 0x9f, 0x12, 0x9b, 0x06, 0x49, 0x3b, 0x6a, 0x38,
	0x73, 0x5d, 0x0a, 0xb4, 0xea, 0xcf, 0x60, 0x38, 0xc7, 0xce, 0x38, 0x24, 0x0d, 0xdf, 0x2c, 0x70,
	0x88, 0x31, 0x9c, 0x63, 0xc3, 0x2e, 0xb8, 0x7d, 0x10, 0xf5, 0xa7, 0xd3, 0x49, 0xda, 0xb8, 0xa5,
	0x4c, 0xee, 0x4a, 0x81, 0x6e, 0xfb, 0x79, 0x18, 0x17, 0x69, 0x66, 0xad, 0x92, 0x7e, 0xaa, 0xc5,
	0x56, 0x49, 0x4b, 0x45, 0x1a, 0xe8, 0x80, 0xad, 0x74, 0xb9, 0xeb, 0xf8, 0x2c, 0xa0, 0xf6, 0x78,
	0x07, 0x09, 0x8f, 0x02, 0x1a, 0xea, 0x0b, 0xca, 0xf4, 0xbe, 0x14, 0x68, 0xcb, 0x9f, 0x47, 0xc4,
	0xf3, 0x7d, 0x60, 0x1b, 0x2c, 0xc4, 0xdb, 0xb5, 0xa8, 0xb6, 0x0b, 0x48, 0x81, 0x16, 0x82, 0xc9,
	0x56, 0xc5, 0x08, 0xfc, 0x14, 0xac, 0x4c, 0xfe, 0x3d, 0x63, 0xb6, 0xfb, 0xd2, 0xa5, 0x81, 0xbe,
	0xa4, 0xb8, 0x50, 0x0a, 0xb4, 0x12, 0x64, 0x10, 0x3c, 0xc3, 0x84, 0xdf, 0x82, 0x8d, 0xe7, 0x8c,
	0x13, 0x2f, 0xb7, 0xcf, 0xcb, 0x6a, 0x02, 0x2d, 0x29, 0xd0, 0x06, 0x2f, 0x22, 0xe0, 0x62, 0x5d,
	0xde, 0x30, 0x59, 0x66, 0x50, 0x66, 0x98, 0x2c, 0x74, 0xb1, 0x0e, 0xbe, 0x00, 0x7a, 0x02, 0xe4,
	0x4e, 0x41, 0x4d, 0x79, 0xde, 0x93, 0x02, 0xe9, 0xbc, 0x84, 0x83, 0x4b, 0xd5, 0x85, 0xce, 0x49,
	0xb7, 0xf5, 0x39, 0xce, 0x49, 0xc3, 0xa5, 0x6a, 0x38, 0x04, 0xed, 0x1c, 0x96, 0x3f, 0x23, 0x0d,
	0x35, 0xc6, 0x43, 0x29, 0x50, 0x9b, 0x5f, 0xcb, 0xc6, 0x6f, 0xe1, 0x08, 0xdf, 0x05, 0x8b, 0x47,
	0xc7, 0x24, 0xb0, 0xbb, 0xb6, 0xbe, 0xa2, 0xcc, 0x6b, 0x52, 0xa0, 0xc5, 0x70, 0x52, 0xc2, 0x09,
	0x06, 0xbf, 0x02, 0xcd, 0xab, 0xc5, 0xe0, 0x84, 0x47, 0xa1, 0xde, 0xdc, 0xd6, 0x76, 0x96, 0xcd,
	0x2d, 0x29, 0x50, 0x6b, 0x98, 0x85, 0xde, 0x67, 0x7d, 0x77, 0x9c, 0x0f, 0xfc, 0x14, 0xcf, 0xaa,
	0xda, 0xbf, 0xd5, 0x40, 0xf3, 0x30, 0x9b, 0x82, 0xf0, 0x63, 0x50, 0x37, 0xf7, 0x8f, 0x0e, 0xa3,
	0x9e, 0xe7, 0x5a, 0xdf, 0xd0, 0x53, 0x15, 0x33, 0x75, 0x73, 0x55, 0x0a, 0x54, 0xef, 0x79, 0xe1,
	0xb4, 0x8e, 0x33, 0x2c, 0xd8, 0x01, 0x0d, 0x4c, 0x5f, 0x91, 0xc0, 0xee, 0xd8, 0x76, 0x90, 0xe4,
	0x4c, 0xdd, 0x7c, 0x47, 0x0a, 0x74, 0x37, 0x48, 0x03, 0xa9, 0x76, 0xb2, 0x8a, 0xf4, 0xe4, 0x6f,
	0xce, 0x99, 0x3c, 0x49, 0x85, 0x63, 0x72, 0x46, 0x08, 0xa7, 0x2a, 0x51, 0x6a, 0x1f, 0x36, 0x27,
	0x79, 0xbc, 0x9b, 0x84, 0xb1, 0x79, 0xef, 0xb5, 0x40, 0x15, 0x29, 0xd0, 0xfa, 0xb0, 0x40, 0x84,
	0x0b, 0xad, 0xe0, 0x0b, 0xb0, 0x96, 0xbd, 0x2b, 0x63, 0xff, 0x6a, 0xb1, 0x7f, 0x2b, 0xf6, 0x5f,
	0xf3, 0x66, 0x15, 0x38, 0x6f, 0x02, 0x7f, 0x06, 0xc6, 0x9c, 0x23, 0x32, 0x1e, 0x66, 0x12, 0x3c,
	0x6d, 0x29, 0x90, 0x31, 0x9c, 0xcb, 0xc4, 0xd7, 0x38, 0xcd, 0x44, 0x4f, 0xa3, 0x30, 0x7a, 0xb2,
	0x2f, 0xca, 0x92, 0xe2, 0xcd, 0x7b, 0x51, 0x7e, 0xd7, 0x40, 0xb3, 0x63, 0x59, 0x51, 0x3f, 0xf2,
	0x08, 0xa7, 0xf6, 0x53, 0x4a, 0x27, 0x49, 0x53, 0x37, 0x7b, 0xe3, 0xa3, 0x47, 0xb2, 0xd0, 0xd5,
	0x5e, 0xff, 0xf5, 0x37, 0xea, 0xf4, 0x09, 0x3f, 0xde, 0xeb, 0xb9, 0xce, 0x6e, 0xd7, 0xe7, 0x9f,
	0xa5, 0x5e, 0xd7, 0x27, 0x5e, 0xc0, 0x7c, 0xfb, 0x80, 0xf2, 0x57, 0x2c, 0x38, 0xd9, 0xa3, 0xea,
	0xeb, 0x91, 0xc3, 0xf6, 0xec, 0xf1, 0x9b, 0x6c, 0xba, 0x4e, 0xd7, 0xe7, 0x8f, 0x49, 0xc8, 0x69,
	0x80, 0x67, 0x87, 0x86, 0x3f, 0x81, 0xcd, 0xf1, 0xbb, 0x4a, 0x3d, 0x6a, 0x71, 0x6a, 0x77, 0xfd,
	0x78, 0xa9, 0x4d, 0x8f, 0x59, 0x27, 0x61, 0x9c, 0x58, 0x86, 0x14, 0x68, 0xd3, 0x2f, 0x65, 0xe1,
	0x39, 0x0e, 0xf0, 0x03, 0x50, 0xeb, 0xfa, 0x36, 0xfd, 0xa5, 0xeb, 0xef, 0xbb, 0x21, 0x8f, 0xe3,
	0xaa, 0x29, 0x05, 0xaa, 0xb9, 0x57, 0x65, 0x9c, 0xe6, 0xc0, 0x87, 0xe0, 0x96, 0xe2, 0xd6, 0xd5,
	0x85, 0x54, 0x11, 0xee, 0xb9, 0x21, 0x4f, 0x1d, 0x7b, 0x85, 0xc3, 0x1f, 0x41, 0xeb, 0xf1, 0xf8,
	0x51, 0xb7, 0x22, 0xee, 0x0e, 0xe9, 0x61, 0xc0, 0x06, 0x2c, 0xa4, 0xc1, 0x33, 0x37, 0x0c, 0xa7,
	0xc9, 0xa2, 0x6e, 0xb3, 0x55, 0x46, 0xc2, 0xe5, 0x7a, 0x38, 0x00, 0x2d, 0x95, 0x36, 0x85, 0x17,
	0x65, 0xa5, 0xf8, 0x20, 0xdf, 0x8f, 0x0f, 0x72, 0x8b, 0x97, 0x29, 0x71, 0xb9, 0x29, 0x74, 0xc0,
	0x1d, 0x05, 0xe6, 0xef, 0x4d, 0xb3, 0x78, 0x38, 0x23, 0x1e, 0xee, 0x0e, 0x2f, 0x94, 0xe1, 0x12,
	0x3b, 0x78, 0x0a, 0x1e, 0x64, 0xbb, 0x28, 0xbe, 0x46, 0xab, 0x6a, 0x05, 0xdf, 0x93, 0x02, 0x3d,
	0xe0, 0xd7, 0xd3, 0xf1, 0xdb, 0x78, 0x42, 0x04, 0xaa, 0x07, 0xcc, 0xb7, 0xa8, 0xbe, 0xb6, 0xad,
	0xed, 0xdc, 0x32, 0x97, 0xa5, 0x40, 0x55, 0x7f, 0x5c, 0xc0, 0x93, 0x3a, 0xfc, 0x04, 0x34, 0xbe,
	0xf3, 0x8f, 0x38, 0x39, 0xa1, 0xf6, 0x93, 0x01, 0xb3, 0x8e, 0x75, 0xa8, 0xba, 0x58, 0x93, 0x02,
	0x35, 0xa2, 0x34, 0x80, 0xb3, 0x3c, 0xf3, 0xf3, 0xb3, 0x0b, 0xa3, 0x72, 0x7e, 0x61, 0x54, 0xde,
	0x5c, 0x18, 0xda, 0xaf, 0x23, 0x43, 0xfb, 0x73, 0x64, 0x68, 0xaf, 0x47, 0x86, 0x76, 0x36, 0x32,
	0xb4, 0xf3, 0x91, 0xa1, 0xfd, 0x33, 0x32, 0xb4, 0xff, 0x46, 0x46, 0xe5, 0xcd, 0xc8, 0xd0, 0xfe,
	0xb8, 0x34, 0x2a, 0x67, 0x97, 0x46, 0xe5, 0xfc, 0xd2, 0xa8, 0xfc, 0x50, 0x0d, 0x39, 0xe1, 0xb4,
	0xb7, 0xa0, 0x56, 0xf7, 0xa3, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x65, 0x57, 0x82, 0xc6, 0xd4,
	0x0a, 0x00, 0x00,
}

func (this *SignRate) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SignRate)
	if !ok {
		that2, ok := that.(SignRate)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.NumSuccess != that1.NumSuccess {
		return false
	}
	if this.NumFailure != that1.NumFailure {
		return false
	}
	return true
}
func (this *ValidatorApiResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ValidatorApiResponse)
	if !ok {
		that2, ok := that.(ValidatorApiResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TempRating != that1.TempRating {
		return false
	}
	if this.NumLeaderSuccess != that1.NumLeaderSuccess {
		return false
	}
	if this.NumLeaderFailure != that1.NumLeaderFailure {
		return false
	}
	if this.NumValidatorSuccess != that1.NumValidatorSuccess {
		return false
	}
	if this.NumValidatorFailure != that1.NumValidatorFailure {
		return false
	}
	if this.NumValidatorIgnoredSignatures != that1.NumValidatorIgnoredSignatures {
		return false
	}
	if this.Rating != that1.Rating {
		return false
	}
	if this.RatingModifier != that1.RatingModifier {
		return false
	}
	if this.TotalNumLeaderSuccess != that1.TotalNumLeaderSuccess {
		return false
	}
	if this.TotalNumLeaderFailure != that1.TotalNumLeaderFailure {
		return false
	}
	if this.TotalNumValidatorSuccess != that1.TotalNumValidatorSuccess {
		return false
	}
	if this.TotalNumValidatorFailure != that1.TotalNumValidatorFailure {
		return false
	}
	if this.TotalNumValidatorIgnoredSignatures != that1.TotalNumValidatorIgnoredSignatures {
		return false
	}
	if this.ShardId != that1.ShardId {
		return false
	}
	if this.ValidatorStatus != that1.ValidatorStatus {
		return false
	}
	return true
}
func (this *PeerAccountData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PeerAccountData)
	if !ok {
		that2, ok := that.(PeerAccountData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.BLSPublicKey, that1.BLSPublicKey) {
		return false
	}
	if !bytes.Equal(this.RewardAddress, that1.RewardAddress) {
		return false
	}
	if this.ShardId != that1.ShardId {
		return false
	}
	if !this.ValidatorSuccessRate.Equal(&that1.ValidatorSuccessRate) {
		return false
	}
	if !this.LeaderSuccessRate.Equal(&that1.LeaderSuccessRate) {
		return false
	}
	if this.ValidatorIgnoredSignaturesRate != that1.ValidatorIgnoredSignaturesRate {
		return false
	}
	if this.Rating != that1.Rating {
		return false
	}
	if this.TempRating != that1.TempRating {
		return false
	}
	{
		__caster := &github_com_ElrondNetwork_elrond_go_data.BigIntCaster{}
		if !__caster.Equal(this.AccumulatedFees, that1.AccumulatedFees) {
			return false
		}
	}
	if this.NumSelectedInSuccessBlocks != that1.NumSelectedInSuccessBlocks {
		return false
	}
	if this.IndexInList != that1.IndexInList {
		return false
	}
	if this.List != that1.List {
		return false
	}
	if this.ConsecutiveProposerMisses != that1.ConsecutiveProposerMisses {
		return false
	}
	if !this.TotalValidatorSuccessRate.Equal(&that1.TotalValidatorSuccessRate) {
		return false
	}
	if !this.TotalLeaderSuccessRate.Equal(&that1.TotalLeaderSuccessRate) {
		return false
	}
	if this.TotalValidatorIgnoredSignaturesRate != that1.TotalValidatorIgnoredSignaturesRate {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if this.UnStakedEpoch != that1.UnStakedEpoch {
		return false
	}
	return true
}
func (this *SignRate) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&state.SignRate{")
	s = append(s, "NumSuccess: "+fmt.Sprintf("%#v", this.NumSuccess)+",\n")
	s = append(s, "NumFailure: "+fmt.Sprintf("%#v", this.NumFailure)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ValidatorApiResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 19)
	s = append(s, "&state.ValidatorApiResponse{")
	s = append(s, "TempRating: "+fmt.Sprintf("%#v", this.TempRating)+",\n")
	s = append(s, "NumLeaderSuccess: "+fmt.Sprintf("%#v", this.NumLeaderSuccess)+",\n")
	s = append(s, "NumLeaderFailure: "+fmt.Sprintf("%#v", this.NumLeaderFailure)+",\n")
	s = append(s, "NumValidatorSuccess: "+fmt.Sprintf("%#v", this.NumValidatorSuccess)+",\n")
	s = append(s, "NumValidatorFailure: "+fmt.Sprintf("%#v", this.NumValidatorFailure)+",\n")
	s = append(s, "NumValidatorIgnoredSignatures: "+fmt.Sprintf("%#v", this.NumValidatorIgnoredSignatures)+",\n")
	s = append(s, "Rating: "+fmt.Sprintf("%#v", this.Rating)+",\n")
	s = append(s, "RatingModifier: "+fmt.Sprintf("%#v", this.RatingModifier)+",\n")
	s = append(s, "TotalNumLeaderSuccess: "+fmt.Sprintf("%#v", this.TotalNumLeaderSuccess)+",\n")
	s = append(s, "TotalNumLeaderFailure: "+fmt.Sprintf("%#v", this.TotalNumLeaderFailure)+",\n")
	s = append(s, "TotalNumValidatorSuccess: "+fmt.Sprintf("%#v", this.TotalNumValidatorSuccess)+",\n")
	s = append(s, "TotalNumValidatorFailure: "+fmt.Sprintf("%#v", this.TotalNumValidatorFailure)+",\n")
	s = append(s, "TotalNumValidatorIgnoredSignatures: "+fmt.Sprintf("%#v", this.TotalNumValidatorIgnoredSignatures)+",\n")
	s = append(s, "ShardId: "+fmt.Sprintf("%#v", this.ShardId)+",\n")
	s = append(s, "ValidatorStatus: "+fmt.Sprintf("%#v", this.ValidatorStatus)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PeerAccountData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 22)
	s = append(s, "&state.PeerAccountData{")
	s = append(s, "BLSPublicKey: "+fmt.Sprintf("%#v", this.BLSPublicKey)+",\n")
	s = append(s, "RewardAddress: "+fmt.Sprintf("%#v", this.RewardAddress)+",\n")
	s = append(s, "ShardId: "+fmt.Sprintf("%#v", this.ShardId)+",\n")
	s = append(s, "ValidatorSuccessRate: "+strings.Replace(this.ValidatorSuccessRate.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "LeaderSuccessRate: "+strings.Replace(this.LeaderSuccessRate.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "ValidatorIgnoredSignaturesRate: "+fmt.Sprintf("%#v", this.ValidatorIgnoredSignaturesRate)+",\n")
	s = append(s, "Rating: "+fmt.Sprintf("%#v", this.Rating)+",\n")
	s = append(s, "TempRating: "+fmt.Sprintf("%#v", this.TempRating)+",\n")
	s = append(s, "AccumulatedFees: "+fmt.Sprintf("%#v", this.AccumulatedFees)+",\n")
	s = append(s, "NumSelectedInSuccessBlocks: "+fmt.Sprintf("%#v", this.NumSelectedInSuccessBlocks)+",\n")
	s = append(s, "IndexInList: "+fmt.Sprintf("%#v", this.IndexInList)+",\n")
	s = append(s, "List: "+fmt.Sprintf("%#v", this.List)+",\n")
	s = append(s, "ConsecutiveProposerMisses: "+fmt.Sprintf("%#v", this.ConsecutiveProposerMisses)+",\n")
	s = append(s, "TotalValidatorSuccessRate: "+strings.Replace(this.TotalValidatorSuccessRate.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "TotalLeaderSuccessRate: "+strings.Replace(this.TotalLeaderSuccessRate.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "TotalValidatorIgnoredSignaturesRate: "+fmt.Sprintf("%#v", this.TotalValidatorIgnoredSignaturesRate)+",\n")
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "UnStakedEpoch: "+fmt.Sprintf("%#v", this.UnStakedEpoch)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringPeerAccountData(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *SignRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignRate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignRate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NumFailure != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumFailure))
		i--
		dAtA[i] = 0x10
	}
	if m.NumSuccess != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumSuccess))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorApiResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorApiResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorApiResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorStatus) > 0 {
		i -= len(m.ValidatorStatus)
		copy(dAtA[i:], m.ValidatorStatus)
		i = encodeVarintPeerAccountData(dAtA, i, uint64(len(m.ValidatorStatus)))
		i--
		dAtA[i] = 0x7a
	}
	if m.ShardId != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.ShardId))
		i--
		dAtA[i] = 0x70
	}
	if m.TotalNumValidatorIgnoredSignatures != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.TotalNumValidatorIgnoredSignatures))
		i--
		dAtA[i] = 0x68
	}
	if m.TotalNumValidatorFailure != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.TotalNumValidatorFailure))
		i--
		dAtA[i] = 0x60
	}
	if m.TotalNumValidatorSuccess != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.TotalNumValidatorSuccess))
		i--
		dAtA[i] = 0x58
	}
	if m.TotalNumLeaderFailure != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.TotalNumLeaderFailure))
		i--
		dAtA[i] = 0x50
	}
	if m.TotalNumLeaderSuccess != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.TotalNumLeaderSuccess))
		i--
		dAtA[i] = 0x48
	}
	if m.RatingModifier != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.RatingModifier))))
		i--
		dAtA[i] = 0x45
	}
	if m.Rating != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Rating))))
		i--
		dAtA[i] = 0x3d
	}
	if m.NumValidatorIgnoredSignatures != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumValidatorIgnoredSignatures))
		i--
		dAtA[i] = 0x30
	}
	if m.NumValidatorFailure != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumValidatorFailure))
		i--
		dAtA[i] = 0x28
	}
	if m.NumValidatorSuccess != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumValidatorSuccess))
		i--
		dAtA[i] = 0x20
	}
	if m.NumLeaderFailure != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumLeaderFailure))
		i--
		dAtA[i] = 0x18
	}
	if m.NumLeaderSuccess != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumLeaderSuccess))
		i--
		dAtA[i] = 0x10
	}
	if m.TempRating != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.TempRating))))
		i--
		dAtA[i] = 0xd
	}
	return len(dAtA) - i, nil
}

func (m *PeerAccountData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PeerAccountData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PeerAccountData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UnStakedEpoch != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.UnStakedEpoch))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.Nonce != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.TotalValidatorIgnoredSignaturesRate != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.TotalValidatorIgnoredSignaturesRate))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	{
		size, err := m.TotalLeaderSuccessRate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPeerAccountData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x7a
	{
		size, err := m.TotalValidatorSuccessRate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPeerAccountData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	if m.ConsecutiveProposerMisses != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.ConsecutiveProposerMisses))
		i--
		dAtA[i] = 0x68
	}
	if len(m.List) > 0 {
		i -= len(m.List)
		copy(dAtA[i:], m.List)
		i = encodeVarintPeerAccountData(dAtA, i, uint64(len(m.List)))
		i--
		dAtA[i] = 0x62
	}
	if m.IndexInList != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.IndexInList))
		i--
		dAtA[i] = 0x58
	}
	if m.NumSelectedInSuccessBlocks != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.NumSelectedInSuccessBlocks))
		i--
		dAtA[i] = 0x50
	}
	{
		__caster := &github_com_ElrondNetwork_elrond_go_data.BigIntCaster{}
		size := __caster.Size(m.AccumulatedFees)
		i -= size
		if _, err := __caster.MarshalTo(m.AccumulatedFees, dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPeerAccountData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.TempRating != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.TempRating))
		i--
		dAtA[i] = 0x40
	}
	if m.Rating != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.Rating))
		i--
		dAtA[i] = 0x38
	}
	if m.ValidatorIgnoredSignaturesRate != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.ValidatorIgnoredSignaturesRate))
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.LeaderSuccessRate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPeerAccountData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.ValidatorSuccessRate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPeerAccountData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ShardId != 0 {
		i = encodeVarintPeerAccountData(dAtA, i, uint64(m.ShardId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintPeerAccountData(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BLSPublicKey) > 0 {
		i -= len(m.BLSPublicKey)
		copy(dAtA[i:], m.BLSPublicKey)
		i = encodeVarintPeerAccountData(dAtA, i, uint64(len(m.BLSPublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPeerAccountData(dAtA []byte, offset int, v uint64) int {
	offset -= sovPeerAccountData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SignRate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumSuccess != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumSuccess))
	}
	if m.NumFailure != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumFailure))
	}
	return n
}

func (m *ValidatorApiResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TempRating != 0 {
		n += 5
	}
	if m.NumLeaderSuccess != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumLeaderSuccess))
	}
	if m.NumLeaderFailure != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumLeaderFailure))
	}
	if m.NumValidatorSuccess != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumValidatorSuccess))
	}
	if m.NumValidatorFailure != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumValidatorFailure))
	}
	if m.NumValidatorIgnoredSignatures != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumValidatorIgnoredSignatures))
	}
	if m.Rating != 0 {
		n += 5
	}
	if m.RatingModifier != 0 {
		n += 5
	}
	if m.TotalNumLeaderSuccess != 0 {
		n += 1 + sovPeerAccountData(uint64(m.TotalNumLeaderSuccess))
	}
	if m.TotalNumLeaderFailure != 0 {
		n += 1 + sovPeerAccountData(uint64(m.TotalNumLeaderFailure))
	}
	if m.TotalNumValidatorSuccess != 0 {
		n += 1 + sovPeerAccountData(uint64(m.TotalNumValidatorSuccess))
	}
	if m.TotalNumValidatorFailure != 0 {
		n += 1 + sovPeerAccountData(uint64(m.TotalNumValidatorFailure))
	}
	if m.TotalNumValidatorIgnoredSignatures != 0 {
		n += 1 + sovPeerAccountData(uint64(m.TotalNumValidatorIgnoredSignatures))
	}
	if m.ShardId != 0 {
		n += 1 + sovPeerAccountData(uint64(m.ShardId))
	}
	l = len(m.ValidatorStatus)
	if l > 0 {
		n += 1 + l + sovPeerAccountData(uint64(l))
	}
	return n
}

func (m *PeerAccountData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BLSPublicKey)
	if l > 0 {
		n += 1 + l + sovPeerAccountData(uint64(l))
	}
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovPeerAccountData(uint64(l))
	}
	if m.ShardId != 0 {
		n += 1 + sovPeerAccountData(uint64(m.ShardId))
	}
	l = m.ValidatorSuccessRate.Size()
	n += 1 + l + sovPeerAccountData(uint64(l))
	l = m.LeaderSuccessRate.Size()
	n += 1 + l + sovPeerAccountData(uint64(l))
	if m.ValidatorIgnoredSignaturesRate != 0 {
		n += 1 + sovPeerAccountData(uint64(m.ValidatorIgnoredSignaturesRate))
	}
	if m.Rating != 0 {
		n += 1 + sovPeerAccountData(uint64(m.Rating))
	}
	if m.TempRating != 0 {
		n += 1 + sovPeerAccountData(uint64(m.TempRating))
	}
	{
		__caster := &github_com_ElrondNetwork_elrond_go_data.BigIntCaster{}
		l = __caster.Size(m.AccumulatedFees)
		n += 1 + l + sovPeerAccountData(uint64(l))
	}
	if m.NumSelectedInSuccessBlocks != 0 {
		n += 1 + sovPeerAccountData(uint64(m.NumSelectedInSuccessBlocks))
	}
	if m.IndexInList != 0 {
		n += 1 + sovPeerAccountData(uint64(m.IndexInList))
	}
	l = len(m.List)
	if l > 0 {
		n += 1 + l + sovPeerAccountData(uint64(l))
	}
	if m.ConsecutiveProposerMisses != 0 {
		n += 1 + sovPeerAccountData(uint64(m.ConsecutiveProposerMisses))
	}
	l = m.TotalValidatorSuccessRate.Size()
	n += 1 + l + sovPeerAccountData(uint64(l))
	l = m.TotalLeaderSuccessRate.Size()
	n += 1 + l + sovPeerAccountData(uint64(l))
	if m.TotalValidatorIgnoredSignaturesRate != 0 {
		n += 2 + sovPeerAccountData(uint64(m.TotalValidatorIgnoredSignaturesRate))
	}
	if m.Nonce != 0 {
		n += 2 + sovPeerAccountData(uint64(m.Nonce))
	}
	if m.UnStakedEpoch != 0 {
		n += 2 + sovPeerAccountData(uint64(m.UnStakedEpoch))
	}
	return n
}

func sovPeerAccountData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPeerAccountData(x uint64) (n int) {
	return sovPeerAccountData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *SignRate) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SignRate{`,
		`NumSuccess:` + fmt.Sprintf("%v", this.NumSuccess) + `,`,
		`NumFailure:` + fmt.Sprintf("%v", this.NumFailure) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ValidatorApiResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ValidatorApiResponse{`,
		`TempRating:` + fmt.Sprintf("%v", this.TempRating) + `,`,
		`NumLeaderSuccess:` + fmt.Sprintf("%v", this.NumLeaderSuccess) + `,`,
		`NumLeaderFailure:` + fmt.Sprintf("%v", this.NumLeaderFailure) + `,`,
		`NumValidatorSuccess:` + fmt.Sprintf("%v", this.NumValidatorSuccess) + `,`,
		`NumValidatorFailure:` + fmt.Sprintf("%v", this.NumValidatorFailure) + `,`,
		`NumValidatorIgnoredSignatures:` + fmt.Sprintf("%v", this.NumValidatorIgnoredSignatures) + `,`,
		`Rating:` + fmt.Sprintf("%v", this.Rating) + `,`,
		`RatingModifier:` + fmt.Sprintf("%v", this.RatingModifier) + `,`,
		`TotalNumLeaderSuccess:` + fmt.Sprintf("%v", this.TotalNumLeaderSuccess) + `,`,
		`TotalNumLeaderFailure:` + fmt.Sprintf("%v", this.TotalNumLeaderFailure) + `,`,
		`TotalNumValidatorSuccess:` + fmt.Sprintf("%v", this.TotalNumValidatorSuccess) + `,`,
		`TotalNumValidatorFailure:` + fmt.Sprintf("%v", this.TotalNumValidatorFailure) + `,`,
		`TotalNumValidatorIgnoredSignatures:` + fmt.Sprintf("%v", this.TotalNumValidatorIgnoredSignatures) + `,`,
		`ShardId:` + fmt.Sprintf("%v", this.ShardId) + `,`,
		`ValidatorStatus:` + fmt.Sprintf("%v", this.ValidatorStatus) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PeerAccountData) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PeerAccountData{`,
		`BLSPublicKey:` + fmt.Sprintf("%v", this.BLSPublicKey) + `,`,
		`RewardAddress:` + fmt.Sprintf("%v", this.RewardAddress) + `,`,
		`ShardId:` + fmt.Sprintf("%v", this.ShardId) + `,`,
		`ValidatorSuccessRate:` + strings.Replace(strings.Replace(this.ValidatorSuccessRate.String(), "SignRate", "SignRate", 1), `&`, ``, 1) + `,`,
		`LeaderSuccessRate:` + strings.Replace(strings.Replace(this.LeaderSuccessRate.String(), "SignRate", "SignRate", 1), `&`, ``, 1) + `,`,
		`ValidatorIgnoredSignaturesRate:` + fmt.Sprintf("%v", this.ValidatorIgnoredSignaturesRate) + `,`,
		`Rating:` + fmt.Sprintf("%v", this.Rating) + `,`,
		`TempRating:` + fmt.Sprintf("%v", this.TempRating) + `,`,
		`AccumulatedFees:` + fmt.Sprintf("%v", this.AccumulatedFees) + `,`,
		`NumSelectedInSuccessBlocks:` + fmt.Sprintf("%v", this.NumSelectedInSuccessBlocks) + `,`,
		`IndexInList:` + fmt.Sprintf("%v", this.IndexInList) + `,`,
		`List:` + fmt.Sprintf("%v", this.List) + `,`,
		`ConsecutiveProposerMisses:` + fmt.Sprintf("%v", this.ConsecutiveProposerMisses) + `,`,
		`TotalValidatorSuccessRate:` + strings.Replace(strings.Replace(this.TotalValidatorSuccessRate.String(), "SignRate", "SignRate", 1), `&`, ``, 1) + `,`,
		`TotalLeaderSuccessRate:` + strings.Replace(strings.Replace(this.TotalLeaderSuccessRate.String(), "SignRate", "SignRate", 1), `&`, ``, 1) + `,`,
		`TotalValidatorIgnoredSignaturesRate:` + fmt.Sprintf("%v", this.TotalValidatorIgnoredSignaturesRate) + `,`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`UnStakedEpoch:` + fmt.Sprintf("%v", this.UnStakedEpoch) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringPeerAccountData(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *SignRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPeerAccountData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSuccess", wireType)
			}
			m.NumSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumFailure", wireType)
			}
			m.NumFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPeerAccountData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorApiResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPeerAccountData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorApiResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorApiResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TempRating", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.TempRating = float32(math.Float32frombits(v))
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumLeaderSuccess", wireType)
			}
			m.NumLeaderSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumLeaderSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumLeaderFailure", wireType)
			}
			m.NumLeaderFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumLeaderFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumValidatorSuccess", wireType)
			}
			m.NumValidatorSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumValidatorSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumValidatorFailure", wireType)
			}
			m.NumValidatorFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumValidatorFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumValidatorIgnoredSignatures", wireType)
			}
			m.NumValidatorIgnoredSignatures = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumValidatorIgnoredSignatures |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rating", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Rating = float32(math.Float32frombits(v))
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field RatingModifier", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.RatingModifier = float32(math.Float32frombits(v))
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalNumLeaderSuccess", wireType)
			}
			m.TotalNumLeaderSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalNumLeaderSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalNumLeaderFailure", wireType)
			}
			m.TotalNumLeaderFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalNumLeaderFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalNumValidatorSuccess", wireType)
			}
			m.TotalNumValidatorSuccess = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalNumValidatorSuccess |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalNumValidatorFailure", wireType)
			}
			m.TotalNumValidatorFailure = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalNumValidatorFailure |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalNumValidatorIgnoredSignatures", wireType)
			}
			m.TotalNumValidatorIgnoredSignatures = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalNumValidatorIgnoredSignatures |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardId", wireType)
			}
			m.ShardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPeerAccountData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PeerAccountData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPeerAccountData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PeerAccountData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PeerAccountData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BLSPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BLSPublicKey = append(m.BLSPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.BLSPublicKey == nil {
				m.BLSPublicKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = append(m.RewardAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.RewardAddress == nil {
				m.RewardAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardId", wireType)
			}
			m.ShardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSuccessRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorSuccessRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderSuccessRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LeaderSuccessRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorIgnoredSignaturesRate", wireType)
			}
			m.ValidatorIgnoredSignaturesRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorIgnoredSignaturesRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rating", wireType)
			}
			m.Rating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TempRating", wireType)
			}
			m.TempRating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TempRating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccumulatedFees", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			{
				__caster := &github_com_ElrondNetwork_elrond_go_data.BigIntCaster{}
				if tmp, err := __caster.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
					return err
				} else {
					m.AccumulatedFees = tmp
				}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumSelectedInSuccessBlocks", wireType)
			}
			m.NumSelectedInSuccessBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumSelectedInSuccessBlocks |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IndexInList", wireType)
			}
			m.IndexInList = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IndexInList |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.List = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveProposerMisses", wireType)
			}
			m.ConsecutiveProposerMisses = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveProposerMisses |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalValidatorSuccessRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalValidatorSuccessRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLeaderSuccessRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalLeaderSuccessRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalValidatorIgnoredSignaturesRate", wireType)
			}
			m.TotalValidatorIgnoredSignaturesRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalValidatorIgnoredSignaturesRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnStakedEpoch", wireType)
			}
			m.UnStakedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnStakedEpoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPeerAccountData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPeerAccountData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPeerAccountData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPeerAccountData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPeerAccountData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPeerAccountData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPeerAccountData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPeerAccountData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPeerAccountData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPeerAccountData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPeerAccountData = fmt.Errorf("proto: unexpected end of group")
)
