package schnorr_test

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/ElrondNetwork/elrond-go-sandbox/crypto/schnorr"
)

func logError(err error) {
	if err != nil {
		fmt.Println(err.Error())
	}
}

func TestGeneratePair(t *testing.T) {
	priv, pub := schnorr.GeneratePair()
	message := string("abcdefg")
	sig, err := priv.Sign([]byte(message))
	logError(err)
	ok, err := pub.Verify([]byte(message), sig)
	logError(err)
	assert.True(t, ok, "Message could not be verified with provided signature")
}

func TestPrivateKeyToByteArray(t *testing.T) {
	priv, pub := schnorr.GeneratePair()
	byteArrayPriv, err := priv.ToByteArray()
	logError(err)
	recreatedPrivateKey, err := schnorr.PrivateKeyFromByteArray(byteArrayPriv)
	logError(err)
	message := string("abcdefg")
	sig, err := recreatedPrivateKey.Sign([]byte(message))
	logError(err)
	ok, err := pub.Verify([]byte(message), sig)
	logError(err)
	assert.True(t, ok, "Message could not be verified with provided signature")
}

func TestPrivateKeyFromByteArray(t *testing.T) {
	message := string("abcdefg")
	sk, err := schnorr.PrivateKeyFromByteArray([]byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32})
	logError(err)
	pub := sk.GeneratePublic()

	sig, err := sk.Sign([]byte(message))
	logError(err)
	ok, err := pub.Verify([]byte(message), sig)
	logError(err)
	assert.True(t, ok, "sig not correct")
}

func TestPublicKeyFromByteArray(t *testing.T) {
	message := string("abcdefg")
	priv, pub := schnorr.GeneratePair()
	byteArrayPublicKey, err := pub.ToByteArray()
	logError(err)
	recreatedPubKey, err := schnorr.PublicKeyFromByteArray(byteArrayPublicKey)
	logError(err)
	sig, err := priv.Sign([]byte(message))
	logError(err)
	ok, err := recreatedPubKey.Verify([]byte(message), sig)
	logError(err)
	assert.True(t, ok, "incorect build of public key from generated byte array")
}