name: Question about the MultiversX node
description: Ask a question
title: "[Question]: "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out the question form! For a faster response, please use our validator's telegram page: https://t.me/MultiversXValidators
  - type: textarea
    id: describe-solution
    attributes:
      label: Please write the desired question
      description: What is misunderstood, not found on docs or anything similar.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/multiversx/mx-chain-go/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
