package txcache

import "errors"

var errNilMempoolHost = errors.New("nil mempool host")
var errNilSelectionSession = errors.New("nil selection session")
var errNilBlockchainInfo = errors.New("nil blockchain info")
var errNilAccountNonceAndBalanceProvider = errors.New("nil account nonce and balance provider")
var errItemAlreadyInCache = errors.New("item already in cache")
var errEmptyBunchOfTransactions = errors.New("empty bunch of transactions")
var errNilBlockBody = errors.New("nil block body")
var errNilHeaderHandler = errors.New("nil header handler")
var errNilBlockHash = errors.New("nil block hash")
var errNilLatestCommitedBlockHash = errors.New("nil latest commited block hash")
var errBlockNotFound = errors.New("block not found")
var errDiscontinuousSequenceOfBlocks = errors.New("discontinuous sequence of blocks")
var errNilTxCache = errors.New("nil tx cache")
var errNotFoundTx = errors.New("tx not found")
var errDiscontinuousBreadcrumbs = errors.New("discontinuous breadcrumbs")
var errBreadcrumbNotFound = errors.New("breadcrumb not found")
var errNonceGap = errors.New("nonce gap")
var errExceededBalance = errors.New("exceeded balance")
var errNonceNotSet = errors.New("nonce not set")
var errReceivedLastNonceNotSet = errors.New("received last nonce not set")
var errInvalidMaxTrackedBlocks = errors.New("bad max tracked blocks")
var errBadBlockWhileMaxTrackedBlocksReached = errors.New("bad block received while max tracked blocks is reached")
