// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block.proto

package block

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Type identifies the type of the block
type Type int32

const (
	TxBlock                  Type = 0
	StateBlock               Type = 1
	PeerBlock                Type = 2
	SmartContractResultBlock Type = 3
	RewardsBlock             Type = 4
	InvalidBlock             Type = 5
)

var Type_name = map[int32]string{
	0: "TxBlock",
	1: "StateBlock",
	2: "PeerBlock",
	3: "SmartContractResultBlock",
	4: "RewardsBlock",
	5: "InvalidBlock",
}

var Type_value = map[string]int32{
	"TxBlock":                  0,
	"StateBlock":               1,
	"PeerBlock":                2,
	"SmartContractResultBlock": 3,
	"RewardsBlock":             4,
	"InvalidBlock":             5,
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

type MiniBlock struct {
	TxHashes        [][]byte `protobuf:"bytes,1,rep,name=TxHashes,proto3" json:"TxHashes,omitempty"`
	ReceiverShardID uint32   `protobuf:"varint,2,opt,name=ReceiverShardID,proto3" json:"ReceiverShardID,omitempty"`
	SenderShardID   uint32   `protobuf:"varint,3,opt,name=SenderShardID,proto3" json:"SenderShardID,omitempty"`
	Type            Type     `protobuf:"varint,4,opt,name=Type,proto3,enum=proto.Type" json:"Type,omitempty"`
}

func (m *MiniBlock) Reset()      { *m = MiniBlock{} }
func (*MiniBlock) ProtoMessage() {}
func (*MiniBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}
func (m *MiniBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MiniBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MiniBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MiniBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniBlock.Merge(m, src)
}
func (m *MiniBlock) XXX_Size() int {
	return m.Size()
}
func (m *MiniBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniBlock.DiscardUnknown(m)
}

var xxx_messageInfo_MiniBlock proto.InternalMessageInfo

func (m *MiniBlock) GetTxHashes() [][]byte {
	if m != nil {
		return m.TxHashes
	}
	return nil
}

func (m *MiniBlock) GetReceiverShardID() uint32 {
	if m != nil {
		return m.ReceiverShardID
	}
	return 0
}

func (m *MiniBlock) GetSenderShardID() uint32 {
	if m != nil {
		return m.SenderShardID
	}
	return 0
}

func (m *MiniBlock) GetType() Type {
	if m != nil {
		return m.Type
	}
	return TxBlock
}

type MiniBlockHeader struct {
	Hash            []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	SenderShardID   uint32 `protobuf:"varint,2,opt,name=SenderShardID,proto3" json:"SenderShardID,omitempty"`
	ReceiverShardID uint32 `protobuf:"varint,3,opt,name=ReceiverShardID,proto3" json:"ReceiverShardID,omitempty"`
	TxCount         uint32 `protobuf:"varint,4,opt,name=TxCount,proto3" json:"TxCount,omitempty"`
	Type            Type   `protobuf:"varint,5,opt,name=Type,proto3,enum=proto.Type" json:"Type,omitempty"`
}

func (m *MiniBlockHeader) Reset()      { *m = MiniBlockHeader{} }
func (*MiniBlockHeader) ProtoMessage() {}
func (*MiniBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}
func (m *MiniBlockHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MiniBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MiniBlockHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MiniBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniBlockHeader.Merge(m, src)
}
func (m *MiniBlockHeader) XXX_Size() int {
	return m.Size()
}
func (m *MiniBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MiniBlockHeader proto.InternalMessageInfo

func (m *MiniBlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MiniBlockHeader) GetSenderShardID() uint32 {
	if m != nil {
		return m.SenderShardID
	}
	return 0
}

func (m *MiniBlockHeader) GetReceiverShardID() uint32 {
	if m != nil {
		return m.ReceiverShardID
	}
	return 0
}

func (m *MiniBlockHeader) GetTxCount() uint32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

func (m *MiniBlockHeader) GetType() Type {
	if m != nil {
		return m.Type
	}
	return TxBlock
}

// PeerChange holds a change in one peer to shard assignation
type PeerChange struct {
	PubKey      []byte `protobuf:"bytes,1,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	ShardIdDest uint32 `protobuf:"varint,2,opt,name=ShardIdDest,proto3" json:"ShardIdDest,omitempty"`
}

func (m *PeerChange) Reset()      { *m = PeerChange{} }
func (*PeerChange) ProtoMessage() {}
func (*PeerChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{2}
}
func (m *PeerChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PeerChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PeerChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PeerChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerChange.Merge(m, src)
}
func (m *PeerChange) XXX_Size() int {
	return m.Size()
}
func (m *PeerChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerChange.DiscardUnknown(m)
}

var xxx_messageInfo_PeerChange proto.InternalMessageInfo

func (m *PeerChange) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PeerChange) GetShardIdDest() uint32 {
	if m != nil {
		return m.ShardIdDest
	}
	return 0
}

// Header holds the metadata of a block. This is the part that is being hashed and run through consensus.
// The header holds the hash of the body and also the link to the previous block header hash
type Header struct {
	Nonce                  uint64            `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	PrevHash               []byte            `protobuf:"bytes,2,opt,name=PrevHash,proto3" json:"PrevHash,omitempty"`
	PrevRandSeed           []byte            `protobuf:"bytes,3,opt,name=PrevRandSeed,proto3" json:"PrevRandSeed,omitempty"`
	RandSeed               []byte            `protobuf:"bytes,4,opt,name=RandSeed,proto3" json:"RandSeed,omitempty"`
	PubKeysBitmap          []byte            `protobuf:"bytes,5,opt,name=PubKeysBitmap,proto3" json:"PubKeysBitmap,omitempty"`
	ShardID                uint32            `protobuf:"varint,6,opt,name=ShardID,proto3" json:"ShardID,omitempty"`
	TimeStamp              uint64            `protobuf:"varint,7,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Round                  uint64            `protobuf:"varint,8,opt,name=Round,proto3" json:"Round,omitempty"`
	Epoch                  uint32            `protobuf:"varint,9,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	BlockBodyType          Type              `protobuf:"varint,10,opt,name=BlockBodyType,proto3,enum=proto.Type" json:"BlockBodyType,omitempty"`
	Signature              []byte            `protobuf:"bytes,11,opt,name=Signature,proto3" json:"Signature,omitempty"`
	LeaderSignature        []byte            `protobuf:"bytes,12,opt,name=LeaderSignature,proto3" json:"LeaderSignature,omitempty"`
	MiniBlockHeaders       []MiniBlockHeader `protobuf:"bytes,13,rep,name=MiniBlockHeaders,proto3" json:"MiniBlockHeaders"`
	PeerChanges            []PeerChange      `protobuf:"bytes,14,rep,name=PeerChanges,proto3" json:"PeerChanges"`
	RootHash               []byte            `protobuf:"bytes,15,opt,name=RootHash,proto3" json:"RootHash,omitempty"`
	ValidatorStatsRootHash []byte            `protobuf:"bytes,16,opt,name=ValidatorStatsRootHash,proto3" json:"ValidatorStatsRootHash,omitempty"`
	MetaBlockHashes        [][]byte          `protobuf:"bytes,17,rep,name=MetaBlockHashes,proto3" json:"MetaBlockHashes,omitempty"`
	TxCount                uint32            `protobuf:"varint,18,opt,name=TxCount,proto3" json:"TxCount,omitempty"`
}

func (m *Header) Reset()      { *m = Header{} }
func (*Header) ProtoMessage() {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{3}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Header.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return m.Size()
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Header) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *Header) GetPrevRandSeed() []byte {
	if m != nil {
		return m.PrevRandSeed
	}
	return nil
}

func (m *Header) GetRandSeed() []byte {
	if m != nil {
		return m.RandSeed
	}
	return nil
}

func (m *Header) GetPubKeysBitmap() []byte {
	if m != nil {
		return m.PubKeysBitmap
	}
	return nil
}

func (m *Header) GetShardID() uint32 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *Header) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Header) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Header) GetEpoch() uint32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Header) GetBlockBodyType() Type {
	if m != nil {
		return m.BlockBodyType
	}
	return TxBlock
}

func (m *Header) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Header) GetLeaderSignature() []byte {
	if m != nil {
		return m.LeaderSignature
	}
	return nil
}

func (m *Header) GetMiniBlockHeaders() []MiniBlockHeader {
	if m != nil {
		return m.MiniBlockHeaders
	}
	return nil
}

func (m *Header) GetPeerChanges() []PeerChange {
	if m != nil {
		return m.PeerChanges
	}
	return nil
}

func (m *Header) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *Header) GetValidatorStatsRootHash() []byte {
	if m != nil {
		return m.ValidatorStatsRootHash
	}
	return nil
}

func (m *Header) GetMetaBlockHashes() [][]byte {
	if m != nil {
		return m.MetaBlockHashes
	}
	return nil
}

func (m *Header) GetTxCount() uint32 {
	if m != nil {
		return m.TxCount
	}
	return 0
}

type BodyHelper struct {
	MiniBlocks []*MiniBlock `protobuf:"bytes,1,rep,name=MiniBlocks,proto3" json:"MiniBlocks,omitempty"`
}

func (m *BodyHelper) Reset()      { *m = BodyHelper{} }
func (*BodyHelper) ProtoMessage() {}
func (*BodyHelper) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{4}
}
func (m *BodyHelper) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BodyHelper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BodyHelper.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BodyHelper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyHelper.Merge(m, src)
}
func (m *BodyHelper) XXX_Size() int {
	return m.Size()
}
func (m *BodyHelper) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyHelper.DiscardUnknown(m)
}

var xxx_messageInfo_BodyHelper proto.InternalMessageInfo

func (m *BodyHelper) GetMiniBlocks() []*MiniBlock {
	if m != nil {
		return m.MiniBlocks
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Type", Type_name, Type_value)
	proto.RegisterType((*MiniBlock)(nil), "proto.MiniBlock")
	proto.RegisterType((*MiniBlockHeader)(nil), "proto.MiniBlockHeader")
	proto.RegisterType((*PeerChange)(nil), "proto.PeerChange")
	proto.RegisterType((*Header)(nil), "proto.Header")
	proto.RegisterType((*BodyHelper)(nil), "proto.BodyHelper")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xf6, 0xe6, 0x0f, 0x32, 0x4e, 0x20, 0xac, 0x2a, 0x64, 0x21, 0x64, 0xa2, 0x88, 0x43, 0x54,
	0xa9, 0xd0, 0x52, 0xa9, 0x52, 0x55, 0xa9, 0x87, 0x40, 0xab, 0xa0, 0x96, 0x0a, 0x6d, 0xa2, 0x1e,
	0x7a, 0xdb, 0xc4, 0xdb, 0xc4, 0x6a, 0xe2, 0x8d, 0xec, 0x35, 0x85, 0x5b, 0x1f, 0xa1, 0xc7, 0x1e,
	0xfa, 0x00, 0x3d, 0xf6, 0x31, 0x38, 0x72, 0xe4, 0x54, 0x15, 0x73, 0xe9, 0x91, 0x47, 0xa8, 0x76,
	0xd6, 0x38, 0x3f, 0xc0, 0xc9, 0xfb, 0x7d, 0x33, 0x3b, 0xf3, 0xcd, 0xb7, 0xbb, 0x06, 0xbb, 0x37,
	0x92, 0xfd, 0x2f, 0x3b, 0x93, 0x50, 0x2a, 0x49, 0x8b, 0xf8, 0xd9, 0x78, 0x32, 0xf0, 0xd5, 0x30,
	0xee, 0xed, 0xf4, 0xe5, 0x78, 0x77, 0x20, 0x07, 0x72, 0x17, 0xe9, 0x5e, 0xfc, 0x19, 0x11, 0x02,
	0x5c, 0x99, 0x5d, 0x8d, 0x1f, 0x04, 0xca, 0x47, 0x7e, 0xe0, 0xb7, 0x74, 0x25, 0xba, 0x01, 0xcb,
	0xdd, 0xd3, 0x36, 0x8f, 0x86, 0x22, 0x72, 0x48, 0x3d, 0xdf, 0xac, 0xb0, 0x0c, 0xd3, 0x26, 0xac,
	0x32, 0xd1, 0x17, 0xfe, 0x89, 0x08, 0x3b, 0x43, 0x1e, 0x7a, 0x87, 0x07, 0x4e, 0xae, 0x4e, 0x9a,
	0x55, 0xb6, 0x48, 0xd3, 0x6d, 0xa8, 0x76, 0x44, 0xe0, 0x4d, 0xf3, 0xf2, 0x98, 0x37, 0x4f, 0xd2,
	0x2d, 0x28, 0x74, 0xcf, 0x26, 0xc2, 0x29, 0xd4, 0x49, 0x73, 0x65, 0xcf, 0x36, 0x7a, 0x76, 0x34,
	0xc5, 0x30, 0xd0, 0xf8, 0x4d, 0x60, 0x35, 0x93, 0xd6, 0x16, 0xdc, 0x13, 0x21, 0xa5, 0x50, 0xd0,
	0x72, 0x1c, 0x52, 0x27, 0xcd, 0x0a, 0xc3, 0xf5, 0xdd, 0x76, 0xb9, 0xfb, 0xda, 0xdd, 0x23, 0x3f,
	0x7f, 0xbf, 0x7c, 0x07, 0x96, 0xba, 0xa7, 0xfb, 0x32, 0x0e, 0x14, 0x6a, 0xab, 0xb2, 0x5b, 0x98,
	0x49, 0x2e, 0x3e, 0x24, 0xf9, 0x2d, 0xc0, 0xb1, 0x10, 0xe1, 0xfe, 0x90, 0x07, 0x03, 0x41, 0xd7,
	0xa1, 0x74, 0x1c, 0xf7, 0xde, 0x89, 0xb3, 0x54, 0x6e, 0x8a, 0x68, 0x1d, 0x6c, 0xd3, 0xcb, 0x3b,
	0x10, 0x91, 0x4a, 0xe5, 0xce, 0x52, 0x8d, 0x9f, 0x45, 0x28, 0xa5, 0x13, 0x3f, 0x82, 0xe2, 0x07,
	0x19, 0xf4, 0x05, 0xd6, 0x28, 0x30, 0x03, 0xf4, 0x41, 0x1d, 0x87, 0xe2, 0x04, 0xbd, 0xc8, 0x61,
	0xf1, 0x0c, 0xd3, 0x06, 0x54, 0xf4, 0x9a, 0xf1, 0xc0, 0xeb, 0x08, 0xe1, 0xe1, 0x98, 0x15, 0x36,
	0xc7, 0xe9, 0xfd, 0x59, 0xbc, 0x60, 0xf6, 0x67, 0xb1, 0x6d, 0xa8, 0x1a, 0xa1, 0x51, 0xcb, 0x57,
	0x63, 0x3e, 0xc1, 0x71, 0x2b, 0x6c, 0x9e, 0xd4, 0x2e, 0xdd, 0xfa, 0x58, 0x32, 0x2e, 0xdd, 0xfa,
	0xb7, 0x09, 0xe5, 0xae, 0x3f, 0x16, 0x1d, 0xc5, 0xc7, 0x13, 0x67, 0x09, 0x55, 0x4f, 0x09, 0x3d,
	0x0f, 0x93, 0x71, 0xe0, 0x39, 0xcb, 0x66, 0x1e, 0x04, 0x9a, 0x7d, 0x33, 0x91, 0xfd, 0xa1, 0x53,
	0xc6, 0x5a, 0x06, 0xd0, 0x67, 0x50, 0xc5, 0xc3, 0x6f, 0x49, 0xef, 0x0c, 0x8d, 0x87, 0xbb, 0xc6,
	0xcf, 0x67, 0xe8, 0xe6, 0x1d, 0x7f, 0x10, 0x70, 0x15, 0x87, 0xc2, 0xb1, 0x51, 0xf8, 0x94, 0xd0,
	0x97, 0xe0, 0x3d, 0xda, 0x3a, 0xcd, 0xa9, 0x60, 0xce, 0x22, 0x4d, 0xdb, 0x50, 0x5b, 0xb8, 0x7b,
	0x91, 0x53, 0xad, 0xe7, 0x9b, 0xf6, 0xde, 0x7a, 0xda, 0x7d, 0x21, 0xdc, 0x2a, 0x9c, 0xff, 0xd9,
	0xb2, 0xd8, 0x9d, 0x5d, 0xf4, 0x25, 0xd8, 0xd3, 0x3b, 0x11, 0x39, 0x2b, 0x58, 0x64, 0x2d, 0x2d,
	0x32, 0x8d, 0xa4, 0xfb, 0x67, 0x73, 0xf1, 0x94, 0xa4, 0x54, 0x78, 0xca, 0xab, 0xe9, 0x29, 0xa5,
	0x98, 0xbe, 0x80, 0xf5, 0x8f, 0x7c, 0xe4, 0x7b, 0x5c, 0xc9, 0xb0, 0xa3, 0xb8, 0x8a, 0xb2, 0xcc,
	0x1a, 0x66, 0x3e, 0x10, 0xd5, 0x16, 0x1c, 0x09, 0xc5, 0x8d, 0x44, 0xf3, 0xd2, 0xd7, 0xf0, 0xa5,
	0x2f, 0xd2, 0xb3, 0xef, 0x80, 0xce, 0xbd, 0x83, 0xc6, 0x6b, 0x00, 0x6d, 0x78, 0x5b, 0x8c, 0x26,
	0x22, 0xa4, 0x4f, 0x01, 0xb2, 0xa1, 0xcd, 0x6f, 0xc3, 0xde, 0xab, 0x2d, 0x9a, 0xc4, 0x66, 0x72,
	0x1e, 0x2b, 0xf3, 0x8e, 0xa8, 0xad, 0x3b, 0x20, 0x57, 0xb3, 0xe8, 0x0a, 0x80, 0x56, 0x2a, 0x0c,
	0x26, 0xb4, 0x0a, 0x65, 0xed, 0x85, 0x81, 0x39, 0xba, 0x09, 0x4e, 0x67, 0xcc, 0x43, 0xb5, 0x2f,
	0x03, 0x15, 0xf2, 0xbe, 0x62, 0x22, 0x8a, 0x47, 0xca, 0x44, 0xf3, 0xb4, 0x06, 0x15, 0x26, 0xbe,
	0xf2, 0xd0, 0x8b, 0x0c, 0x53, 0xd0, 0xcc, 0x61, 0x70, 0xa2, 0x3d, 0x30, 0x4c, 0xb1, 0xf5, 0xea,
	0xe2, 0xca, 0xb5, 0x2e, 0xaf, 0x5c, 0xeb, 0xe6, 0xca, 0x25, 0xdf, 0x12, 0x97, 0xfc, 0x4a, 0x5c,
	0x72, 0x9e, 0xb8, 0xe4, 0x22, 0x71, 0xc9, 0xdf, 0xc4, 0x25, 0xff, 0x12, 0xd7, 0xba, 0x49, 0x5c,
	0xf2, 0xfd, 0xda, 0xb5, 0x2e, 0xae, 0x5d, 0xeb, 0xf2, 0xda, 0xb5, 0x3e, 0x15, 0xf1, 0x1f, 0xdb,
	0x2b, 0xe1, 0x3c, 0xcf, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x05, 0x51, 0x6c, 0x73, 0x05,
	0x00, 0x00,
}

func (x Type) String() string {
	s, ok := Type_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *MiniBlock) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MiniBlock)
	if !ok {
		that2, ok := that.(MiniBlock)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.TxHashes) != len(that1.TxHashes) {
		return false
	}
	for i := range this.TxHashes {
		if !bytes.Equal(this.TxHashes[i], that1.TxHashes[i]) {
			return false
		}
	}
	if this.ReceiverShardID != that1.ReceiverShardID {
		return false
	}
	if this.SenderShardID != that1.SenderShardID {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	return true
}
func (this *MiniBlockHeader) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MiniBlockHeader)
	if !ok {
		that2, ok := that.(MiniBlockHeader)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	if this.SenderShardID != that1.SenderShardID {
		return false
	}
	if this.ReceiverShardID != that1.ReceiverShardID {
		return false
	}
	if this.TxCount != that1.TxCount {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	return true
}
func (this *PeerChange) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PeerChange)
	if !ok {
		that2, ok := that.(PeerChange)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.PubKey, that1.PubKey) {
		return false
	}
	if this.ShardIdDest != that1.ShardIdDest {
		return false
	}
	return true
}
func (this *Header) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Header)
	if !ok {
		that2, ok := that.(Header)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Nonce != that1.Nonce {
		return false
	}
	if !bytes.Equal(this.PrevHash, that1.PrevHash) {
		return false
	}
	if !bytes.Equal(this.PrevRandSeed, that1.PrevRandSeed) {
		return false
	}
	if !bytes.Equal(this.RandSeed, that1.RandSeed) {
		return false
	}
	if !bytes.Equal(this.PubKeysBitmap, that1.PubKeysBitmap) {
		return false
	}
	if this.ShardID != that1.ShardID {
		return false
	}
	if this.TimeStamp != that1.TimeStamp {
		return false
	}
	if this.Round != that1.Round {
		return false
	}
	if this.Epoch != that1.Epoch {
		return false
	}
	if this.BlockBodyType != that1.BlockBodyType {
		return false
	}
	if !bytes.Equal(this.Signature, that1.Signature) {
		return false
	}
	if !bytes.Equal(this.LeaderSignature, that1.LeaderSignature) {
		return false
	}
	if len(this.MiniBlockHeaders) != len(that1.MiniBlockHeaders) {
		return false
	}
	for i := range this.MiniBlockHeaders {
		if !this.MiniBlockHeaders[i].Equal(&that1.MiniBlockHeaders[i]) {
			return false
		}
	}
	if len(this.PeerChanges) != len(that1.PeerChanges) {
		return false
	}
	for i := range this.PeerChanges {
		if !this.PeerChanges[i].Equal(&that1.PeerChanges[i]) {
			return false
		}
	}
	if !bytes.Equal(this.RootHash, that1.RootHash) {
		return false
	}
	if !bytes.Equal(this.ValidatorStatsRootHash, that1.ValidatorStatsRootHash) {
		return false
	}
	if len(this.MetaBlockHashes) != len(that1.MetaBlockHashes) {
		return false
	}
	for i := range this.MetaBlockHashes {
		if !bytes.Equal(this.MetaBlockHashes[i], that1.MetaBlockHashes[i]) {
			return false
		}
	}
	if this.TxCount != that1.TxCount {
		return false
	}
	return true
}
func (this *BodyHelper) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BodyHelper)
	if !ok {
		that2, ok := that.(BodyHelper)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.MiniBlocks) != len(that1.MiniBlocks) {
		return false
	}
	for i := range this.MiniBlocks {
		if !this.MiniBlocks[i].Equal(that1.MiniBlocks[i]) {
			return false
		}
	}
	return true
}
func (this *MiniBlock) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&block.MiniBlock{")
	s = append(s, "TxHashes: "+fmt.Sprintf("%#v", this.TxHashes)+",\n")
	s = append(s, "ReceiverShardID: "+fmt.Sprintf("%#v", this.ReceiverShardID)+",\n")
	s = append(s, "SenderShardID: "+fmt.Sprintf("%#v", this.SenderShardID)+",\n")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MiniBlockHeader) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&block.MiniBlockHeader{")
	s = append(s, "Hash: "+fmt.Sprintf("%#v", this.Hash)+",\n")
	s = append(s, "SenderShardID: "+fmt.Sprintf("%#v", this.SenderShardID)+",\n")
	s = append(s, "ReceiverShardID: "+fmt.Sprintf("%#v", this.ReceiverShardID)+",\n")
	s = append(s, "TxCount: "+fmt.Sprintf("%#v", this.TxCount)+",\n")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *PeerChange) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&block.PeerChange{")
	s = append(s, "PubKey: "+fmt.Sprintf("%#v", this.PubKey)+",\n")
	s = append(s, "ShardIdDest: "+fmt.Sprintf("%#v", this.ShardIdDest)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Header) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 22)
	s = append(s, "&block.Header{")
	s = append(s, "Nonce: "+fmt.Sprintf("%#v", this.Nonce)+",\n")
	s = append(s, "PrevHash: "+fmt.Sprintf("%#v", this.PrevHash)+",\n")
	s = append(s, "PrevRandSeed: "+fmt.Sprintf("%#v", this.PrevRandSeed)+",\n")
	s = append(s, "RandSeed: "+fmt.Sprintf("%#v", this.RandSeed)+",\n")
	s = append(s, "PubKeysBitmap: "+fmt.Sprintf("%#v", this.PubKeysBitmap)+",\n")
	s = append(s, "ShardID: "+fmt.Sprintf("%#v", this.ShardID)+",\n")
	s = append(s, "TimeStamp: "+fmt.Sprintf("%#v", this.TimeStamp)+",\n")
	s = append(s, "Round: "+fmt.Sprintf("%#v", this.Round)+",\n")
	s = append(s, "Epoch: "+fmt.Sprintf("%#v", this.Epoch)+",\n")
	s = append(s, "BlockBodyType: "+fmt.Sprintf("%#v", this.BlockBodyType)+",\n")
	s = append(s, "Signature: "+fmt.Sprintf("%#v", this.Signature)+",\n")
	s = append(s, "LeaderSignature: "+fmt.Sprintf("%#v", this.LeaderSignature)+",\n")
	if this.MiniBlockHeaders != nil {
		vs := make([]MiniBlockHeader, len(this.MiniBlockHeaders))
		for i := range vs {
			vs[i] = this.MiniBlockHeaders[i]
		}
		s = append(s, "MiniBlockHeaders: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	if this.PeerChanges != nil {
		vs := make([]PeerChange, len(this.PeerChanges))
		for i := range vs {
			vs[i] = this.PeerChanges[i]
		}
		s = append(s, "PeerChanges: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "RootHash: "+fmt.Sprintf("%#v", this.RootHash)+",\n")
	s = append(s, "ValidatorStatsRootHash: "+fmt.Sprintf("%#v", this.ValidatorStatsRootHash)+",\n")
	s = append(s, "MetaBlockHashes: "+fmt.Sprintf("%#v", this.MetaBlockHashes)+",\n")
	s = append(s, "TxCount: "+fmt.Sprintf("%#v", this.TxCount)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *BodyHelper) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&block.BodyHelper{")
	if this.MiniBlocks != nil {
		s = append(s, "MiniBlocks: "+fmt.Sprintf("%#v", this.MiniBlocks)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringBlock(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *MiniBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MiniBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MiniBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x20
	}
	if m.SenderShardID != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.SenderShardID))
		i--
		dAtA[i] = 0x18
	}
	if m.ReceiverShardID != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.ReceiverShardID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxHashes) > 0 {
		for iNdEx := len(m.TxHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TxHashes[iNdEx])
			copy(dAtA[i:], m.TxHashes[iNdEx])
			i = encodeVarintBlock(dAtA, i, uint64(len(m.TxHashes[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MiniBlockHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MiniBlockHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MiniBlockHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x28
	}
	if m.TxCount != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.TxCount))
		i--
		dAtA[i] = 0x20
	}
	if m.ReceiverShardID != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.ReceiverShardID))
		i--
		dAtA[i] = 0x18
	}
	if m.SenderShardID != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.SenderShardID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PeerChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PeerChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PeerChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ShardIdDest != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.ShardIdDest))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Header) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxCount != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.TxCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.MetaBlockHashes) > 0 {
		for iNdEx := len(m.MetaBlockHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MetaBlockHashes[iNdEx])
			copy(dAtA[i:], m.MetaBlockHashes[iNdEx])
			i = encodeVarintBlock(dAtA, i, uint64(len(m.MetaBlockHashes[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if len(m.ValidatorStatsRootHash) > 0 {
		i -= len(m.ValidatorStatsRootHash)
		copy(dAtA[i:], m.ValidatorStatsRootHash)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.ValidatorStatsRootHash)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.RootHash) > 0 {
		i -= len(m.RootHash)
		copy(dAtA[i:], m.RootHash)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.RootHash)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.PeerChanges) > 0 {
		for iNdEx := len(m.PeerChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PeerChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBlock(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.MiniBlockHeaders) > 0 {
		for iNdEx := len(m.MiniBlockHeaders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MiniBlockHeaders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBlock(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.LeaderSignature) > 0 {
		i -= len(m.LeaderSignature)
		copy(dAtA[i:], m.LeaderSignature)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.LeaderSignature)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x5a
	}
	if m.BlockBodyType != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.BlockBodyType))
		i--
		dAtA[i] = 0x50
	}
	if m.Epoch != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x48
	}
	if m.Round != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x40
	}
	if m.TimeStamp != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.TimeStamp))
		i--
		dAtA[i] = 0x38
	}
	if m.ShardID != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.ShardID))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PubKeysBitmap) > 0 {
		i -= len(m.PubKeysBitmap)
		copy(dAtA[i:], m.PubKeysBitmap)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.PubKeysBitmap)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RandSeed) > 0 {
		i -= len(m.RandSeed)
		copy(dAtA[i:], m.RandSeed)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.RandSeed)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PrevRandSeed) > 0 {
		i -= len(m.PrevRandSeed)
		copy(dAtA[i:], m.PrevRandSeed)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.PrevRandSeed)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PrevHash) > 0 {
		i -= len(m.PrevHash)
		copy(dAtA[i:], m.PrevHash)
		i = encodeVarintBlock(dAtA, i, uint64(len(m.PrevHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintBlock(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BodyHelper) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BodyHelper) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BodyHelper) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MiniBlocks) > 0 {
		for iNdEx := len(m.MiniBlocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MiniBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBlock(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintBlock(dAtA []byte, offset int, v uint64) int {
	offset -= sovBlock(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MiniBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TxHashes) > 0 {
		for _, b := range m.TxHashes {
			l = len(b)
			n += 1 + l + sovBlock(uint64(l))
		}
	}
	if m.ReceiverShardID != 0 {
		n += 1 + sovBlock(uint64(m.ReceiverShardID))
	}
	if m.SenderShardID != 0 {
		n += 1 + sovBlock(uint64(m.SenderShardID))
	}
	if m.Type != 0 {
		n += 1 + sovBlock(uint64(m.Type))
	}
	return n
}

func (m *MiniBlockHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	if m.SenderShardID != 0 {
		n += 1 + sovBlock(uint64(m.SenderShardID))
	}
	if m.ReceiverShardID != 0 {
		n += 1 + sovBlock(uint64(m.ReceiverShardID))
	}
	if m.TxCount != 0 {
		n += 1 + sovBlock(uint64(m.TxCount))
	}
	if m.Type != 0 {
		n += 1 + sovBlock(uint64(m.Type))
	}
	return n
}

func (m *PeerChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	if m.ShardIdDest != 0 {
		n += 1 + sovBlock(uint64(m.ShardIdDest))
	}
	return n
}

func (m *Header) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovBlock(uint64(m.Nonce))
	}
	l = len(m.PrevHash)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	l = len(m.PrevRandSeed)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	l = len(m.RandSeed)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	l = len(m.PubKeysBitmap)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	if m.ShardID != 0 {
		n += 1 + sovBlock(uint64(m.ShardID))
	}
	if m.TimeStamp != 0 {
		n += 1 + sovBlock(uint64(m.TimeStamp))
	}
	if m.Round != 0 {
		n += 1 + sovBlock(uint64(m.Round))
	}
	if m.Epoch != 0 {
		n += 1 + sovBlock(uint64(m.Epoch))
	}
	if m.BlockBodyType != 0 {
		n += 1 + sovBlock(uint64(m.BlockBodyType))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	l = len(m.LeaderSignature)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	if len(m.MiniBlockHeaders) > 0 {
		for _, e := range m.MiniBlockHeaders {
			l = e.Size()
			n += 1 + l + sovBlock(uint64(l))
		}
	}
	if len(m.PeerChanges) > 0 {
		for _, e := range m.PeerChanges {
			l = e.Size()
			n += 1 + l + sovBlock(uint64(l))
		}
	}
	l = len(m.RootHash)
	if l > 0 {
		n += 1 + l + sovBlock(uint64(l))
	}
	l = len(m.ValidatorStatsRootHash)
	if l > 0 {
		n += 2 + l + sovBlock(uint64(l))
	}
	if len(m.MetaBlockHashes) > 0 {
		for _, b := range m.MetaBlockHashes {
			l = len(b)
			n += 2 + l + sovBlock(uint64(l))
		}
	}
	if m.TxCount != 0 {
		n += 2 + sovBlock(uint64(m.TxCount))
	}
	return n
}

func (m *BodyHelper) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MiniBlocks) > 0 {
		for _, e := range m.MiniBlocks {
			l = e.Size()
			n += 1 + l + sovBlock(uint64(l))
		}
	}
	return n
}

func sovBlock(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBlock(x uint64) (n int) {
	return sovBlock(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *MiniBlock) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MiniBlock{`,
		`TxHashes:` + fmt.Sprintf("%v", this.TxHashes) + `,`,
		`ReceiverShardID:` + fmt.Sprintf("%v", this.ReceiverShardID) + `,`,
		`SenderShardID:` + fmt.Sprintf("%v", this.SenderShardID) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MiniBlockHeader) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MiniBlockHeader{`,
		`Hash:` + fmt.Sprintf("%v", this.Hash) + `,`,
		`SenderShardID:` + fmt.Sprintf("%v", this.SenderShardID) + `,`,
		`ReceiverShardID:` + fmt.Sprintf("%v", this.ReceiverShardID) + `,`,
		`TxCount:` + fmt.Sprintf("%v", this.TxCount) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PeerChange) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PeerChange{`,
		`PubKey:` + fmt.Sprintf("%v", this.PubKey) + `,`,
		`ShardIdDest:` + fmt.Sprintf("%v", this.ShardIdDest) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Header) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForMiniBlockHeaders := "[]MiniBlockHeader{"
	for _, f := range this.MiniBlockHeaders {
		repeatedStringForMiniBlockHeaders += strings.Replace(strings.Replace(f.String(), "MiniBlockHeader", "MiniBlockHeader", 1), `&`, ``, 1) + ","
	}
	repeatedStringForMiniBlockHeaders += "}"
	repeatedStringForPeerChanges := "[]PeerChange{"
	for _, f := range this.PeerChanges {
		repeatedStringForPeerChanges += strings.Replace(strings.Replace(f.String(), "PeerChange", "PeerChange", 1), `&`, ``, 1) + ","
	}
	repeatedStringForPeerChanges += "}"
	s := strings.Join([]string{`&Header{`,
		`Nonce:` + fmt.Sprintf("%v", this.Nonce) + `,`,
		`PrevHash:` + fmt.Sprintf("%v", this.PrevHash) + `,`,
		`PrevRandSeed:` + fmt.Sprintf("%v", this.PrevRandSeed) + `,`,
		`RandSeed:` + fmt.Sprintf("%v", this.RandSeed) + `,`,
		`PubKeysBitmap:` + fmt.Sprintf("%v", this.PubKeysBitmap) + `,`,
		`ShardID:` + fmt.Sprintf("%v", this.ShardID) + `,`,
		`TimeStamp:` + fmt.Sprintf("%v", this.TimeStamp) + `,`,
		`Round:` + fmt.Sprintf("%v", this.Round) + `,`,
		`Epoch:` + fmt.Sprintf("%v", this.Epoch) + `,`,
		`BlockBodyType:` + fmt.Sprintf("%v", this.BlockBodyType) + `,`,
		`Signature:` + fmt.Sprintf("%v", this.Signature) + `,`,
		`LeaderSignature:` + fmt.Sprintf("%v", this.LeaderSignature) + `,`,
		`MiniBlockHeaders:` + repeatedStringForMiniBlockHeaders + `,`,
		`PeerChanges:` + repeatedStringForPeerChanges + `,`,
		`RootHash:` + fmt.Sprintf("%v", this.RootHash) + `,`,
		`ValidatorStatsRootHash:` + fmt.Sprintf("%v", this.ValidatorStatsRootHash) + `,`,
		`MetaBlockHashes:` + fmt.Sprintf("%v", this.MetaBlockHashes) + `,`,
		`TxCount:` + fmt.Sprintf("%v", this.TxCount) + `,`,
		`}`,
	}, "")
	return s
}
func (this *BodyHelper) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForMiniBlocks := "[]*MiniBlock{"
	for _, f := range this.MiniBlocks {
		repeatedStringForMiniBlocks += strings.Replace(f.String(), "MiniBlock", "MiniBlock", 1) + ","
	}
	repeatedStringForMiniBlocks += "}"
	s := strings.Join([]string{`&BodyHelper{`,
		`MiniBlocks:` + repeatedStringForMiniBlocks + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringBlock(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *MiniBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MiniBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MiniBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHashes = append(m.TxHashes, make([]byte, postIndex-iNdEx))
			copy(m.TxHashes[len(m.TxHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverShardID", wireType)
			}
			m.ReceiverShardID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverShardID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderShardID", wireType)
			}
			m.SenderShardID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderShardID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MiniBlockHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MiniBlockHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MiniBlockHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderShardID", wireType)
			}
			m.SenderShardID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderShardID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverShardID", wireType)
			}
			m.ReceiverShardID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverShardID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxCount", wireType)
			}
			m.TxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PeerChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PeerChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PeerChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = append(m.PubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKey == nil {
				m.PubKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardIdDest", wireType)
			}
			m.ShardIdDest = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardIdDest |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Header) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Header: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Header: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevHash = append(m.PrevHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PrevHash == nil {
				m.PrevHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevRandSeed", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevRandSeed = append(m.PrevRandSeed[:0], dAtA[iNdEx:postIndex]...)
			if m.PrevRandSeed == nil {
				m.PrevRandSeed = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandSeed", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RandSeed = append(m.RandSeed[:0], dAtA[iNdEx:postIndex]...)
			if m.RandSeed == nil {
				m.RandSeed = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeysBitmap", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeysBitmap = append(m.PubKeysBitmap[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKeysBitmap == nil {
				m.PubKeysBitmap = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardID", wireType)
			}
			m.ShardID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeStamp", wireType)
			}
			m.TimeStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeStamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockBodyType", wireType)
			}
			m.BlockBodyType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockBodyType |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeaderSignature = append(m.LeaderSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.LeaderSignature == nil {
				m.LeaderSignature = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MiniBlockHeaders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MiniBlockHeaders = append(m.MiniBlockHeaders, MiniBlockHeader{})
			if err := m.MiniBlockHeaders[len(m.MiniBlockHeaders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerChanges = append(m.PeerChanges, PeerChange{})
			if err := m.PeerChanges[len(m.PeerChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHash = append(m.RootHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RootHash == nil {
				m.RootHash = []byte{}
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorStatsRootHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorStatsRootHash = append(m.ValidatorStatsRootHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorStatsRootHash == nil {
				m.ValidatorStatsRootHash = []byte{}
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaBlockHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaBlockHashes = append(m.MetaBlockHashes, make([]byte, postIndex-iNdEx))
			copy(m.MetaBlockHashes[len(m.MetaBlockHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxCount", wireType)
			}
			m.TxCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BodyHelper) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBlock
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BodyHelper: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BodyHelper: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MiniBlocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBlock
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBlock
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MiniBlocks = append(m.MiniBlocks, &MiniBlock{})
			if err := m.MiniBlocks[len(m.MiniBlocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBlock(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBlock
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBlock(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBlock
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBlock
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBlock
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBlock
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBlock
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBlock        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBlock          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBlock = fmt.Errorf("proto: unexpected end of group")
)
