name: Automatic auditing (proxy workflow)

on:
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    forward-request:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger automatic auditing
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  gh workflow run sample.yml --repo multiversx/mx-auto-audit
